=== openhab/openhab-core/bundles/org.openhab.core.config.core/schema/config-description-1.0.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:config-description="https://openhab.org/schemas/config-description/v1.0.0"
	targetNamespace="https://openhab.org/schemas/config-description/v1.0.0">

	<xs:element name="config-descriptions">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="config-description" type="config-description:configDescription" minOccurs="1"
					maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="config-description" type="config-description:configDescription"/>

	<xs:simpleType name="idRestrictionPattern">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Za-z0-9\-_]+"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="uriRestrictionPattern">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Za-z0-9\-_]+(:[A-Za-z0-9\-_]+){1,2}"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="configDescription">
		<xs:sequence>
			<xs:element name="parameter-group" type="config-description:parameterGroup" minOccurs="0"
				maxOccurs="unbounded"/>
			<xs:element name="parameter" type="config-description:parameter" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="uri" type="config-description:uriRestrictionPattern" use="optional"/>
	</xs:complexType>

	<xs:complexType name="parameter">
		<xs:all>
			<xs:element name="context" type="config-description:contextType" minOccurs="0"/>
			<!-- deprecated element "required" -->
			<xs:element name="required" type="xs:boolean" default="false" minOccurs="0"/>
			<xs:element name="default" type="xs:string" minOccurs="0"/>
			<xs:element name="label" type="xs:string" minOccurs="0"/>
			<xs:element name="description" type="xs:string" minOccurs="0"/>
			<xs:element name="options" type="config-description:optionsType" minOccurs="0"/>
			<xs:element name="limitToOptions" type="xs:boolean" minOccurs="0"/>
			<xs:element name="filter" type="config-description:filterType" minOccurs="0"/>
			<xs:element name="advanced" type="xs:boolean" minOccurs="0"/>
			<xs:element name="verify" type="xs:boolean" minOccurs="0"/>
			<xs:element name="multipleLimit" type="xs:integer" minOccurs="0"/>
			<xs:element name="unitLabel" type="xs:string" minOccurs="0"/>
		</xs:all>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="type" type="config-description:parameterType" use="required"/>
		<xs:attribute name="groupName" type="xs:string"/>
		<xs:attribute name="min" type="xs:decimal"/>
		<xs:attribute name="max" type="xs:decimal"/>
		<xs:attribute name="step" type="xs:decimal"/>
		<xs:attribute name="pattern" type="xs:string"/>
		<xs:attribute name="required" type="xs:boolean"/>
		<xs:attribute name="readOnly" type="xs:boolean"/>
		<xs:attribute name="multiple" type="xs:boolean"/>
		<xs:attribute name="unit" type="config-description:unitType"/>
		<xs:attribute name="dynamic" type="xs:boolean"/>
	</xs:complexType>

	<xs:complexType name="parameterGroup">
		<xs:all>
			<xs:element name="label" type="xs:string" minOccurs="0"/>
			<xs:element name="description" type="xs:string" minOccurs="0"/>
			<xs:element name="context" type="config-description:contextType" minOccurs="0"/>
			<xs:element name="advanced" type="xs:boolean" minOccurs="0"/>
		</xs:all>
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="optionsType">
		<xs:sequence>
			<xs:element name="option" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="value" type="xs:string" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="filterType">
		<xs:sequence>
			<xs:element name="criteria" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="name" type="xs:string" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="parameterType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="text"/>
			<xs:enumeration value="integer"/>
			<xs:enumeration value="decimal"/>
			<xs:enumeration value="boolean"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="unitType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="A"/>
			<xs:enumeration value="cd"/>
			<xs:enumeration value="K"/>
			<xs:enumeration value="kg"/>
			<xs:enumeration value="m"/>
			<xs:enumeration value="mol"/>
			<xs:enumeration value="s"/>
			<xs:enumeration value="Bq"/>
			<xs:enumeration value="C"/>
			<xs:enumeration value="F"/>
			<xs:enumeration value="Gy"/>
			<xs:enumeration value="H"/>
			<xs:enumeration value="Hz"/>
			<xs:enumeration value="J"/>
			<xs:enumeration value="kat"/>
			<xs:enumeration value="lm"/>
			<xs:enumeration value="lx"/>
			<xs:enumeration value="N"/>
			<xs:enumeration value="Pa"/>
			<xs:enumeration value="rad"/>
			<xs:enumeration value="S"/>
			<xs:enumeration value="sr"/>
			<xs:enumeration value="Sv"/>
			<xs:enumeration value="T"/>
			<xs:enumeration value="V"/>
			<xs:enumeration value="W"/>
			<xs:enumeration value="Wb"/>
			<xs:enumeration value="Cel"/>
			<xs:enumeration value="Ω"/>
			<xs:enumeration value="g"/>
			<xs:enumeration value="m/s2"/>
			<xs:enumeration value="m2v"/>
			<xs:enumeration value="m3"/>
			<xs:enumeration value="kph"/>
			<xs:enumeration value="%"/>
			<xs:enumeration value="l"/>
			<xs:enumeration value="ms"/>
			<xs:enumeration value="min"/>
			<xs:enumeration value="h"/>
			<xs:enumeration value="d"/>
			<xs:enumeration value="week"/>
			<xs:enumeration value="y"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="configDescriptionRef">
		<xs:attribute name="uri" type="config-description:uriRestrictionPattern" use="required"/>
	</xs:complexType>

	<xs:simpleType name="contextType">
		<xs:union>
			<xs:simpleType>
				<!-- old behavior: allow any non empty string -->
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
				</xs:restriction>
			</xs:simpleType>
			<xs:simpleType>
				<!-- enhanced behavior: allow "special meaning" options (so IDE can suggest them) -->
				<xs:restriction base="xs:string">
					<xs:enumeration value="channel"/>
					<xs:enumeration value="channel-type"/>
					<xs:enumeration value="color"/>
					<xs:enumeration value="cronexpression"/>
					<xs:enumeration value="date"/>
					<xs:enumeration value="datetime"/>
					<xs:enumeration value="dayOfWeek"/>
					<xs:enumeration value="email"/>
					<xs:enumeration value="group"/>
					<xs:enumeration value="item"/>
					<xs:enumeration value="location"/>
					<xs:enumeration value="mac-address"/>
					<xs:enumeration value="month"/>
					<xs:enumeration value="network-address"/>
					<xs:enumeration value="network-interface"/>
					<xs:enumeration value="page"/>
					<xs:enumeration value="password"/>
					<xs:enumeration value="password-create"/>
					<xs:enumeration value="persistence-service"/>
					<xs:enumeration value="props"/>
					<xs:enumeration value="qrcode"/>
					<xs:enumeration value="rule"/>
					<xs:enumeration value="script"/>
					<xs:enumeration value="serial-port"/>
					<xs:enumeration value="service"/>
					<xs:enumeration value="tag"/>
					<xs:enumeration value="telephone"/>
					<xs:enumeration value="thing"/>
					<xs:enumeration value="time"/>
					<xs:enumeration value="url"/>
					<xs:enumeration value="week"/>
					<xs:enumeration value="widget"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:union>
	</xs:simpleType>

</xs:schema>

=== openhab/openhab-core/bundles/org.openhab.core.test.magic/src/main/resources/ESH-INF/config/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config-description:config-descriptions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:config-description="http://eclipse.org/smarthome/schemas/config-description/v1.0.0"
	xsi:schemaLocation="http://eclipse.org/smarthome/schemas/config-description/v1.0.0
	http://eclipse.org/smarthome/schemas/config-description-1.0.0.xsd">

	<config-description uri="test:magic">
		<parameter-group name="group_normal">
			<label>Group</label>
			<description>A group of configuration parameters.</description>
			<advanced>false</advanced>
		</parameter-group>
		<parameter-group name="group_advanced">
			<label>Group (advanced)</label>
			<description>A group of advanced configuration parameters.</description>
			<advanced>true</advanced>
		</parameter-group>

		<parameter name="text" type="text" groupName="group_normal">
			<label>Text</label>
			<description>A grouped text parameter.</description>
			<default>myText</default>
		</parameter>
		<parameter name="bool" type="boolean" groupName="group_normal">
			<label>Switch</label>
			<description>A grouped boolean parameter.</description>
			<default>false</default>
		</parameter>
		<parameter name="decimal" type="decimal" groupName="group_normal">
			<label>Decimal</label>
			<description>A grouped decimal parameter.</description>
			<default>3.141592</default>
		</parameter>
		<parameter name="integer" type="integer" groupName="group_normal">
			<label>Integer</label>
			<description>A grouped integer parameter.</description>
			<default>42</default>
		</parameter>

		<parameter name="text_advanced" type="text" groupName="group_advanced">
			<label>Text</label>
			<description>A grouped text parameter.</description>
			<default>myText</default>
		</parameter>
		<parameter name="boolean_advanced" type="boolean" groupName="group_advanced">
			<label>Switch</label>
			<description>A grouped boolean parameter.</description>
			<default>false</default>
		</parameter>
		<parameter name="decimal_advanced" type="decimal" groupName="group_advanced">
			<label>Decimal</label>
			<description>A grouped decimal parameter.</description>
			<default>3.141592</default>
		</parameter>
		<parameter name="integer_advanced" type="integer" groupName="group_advanced">
			<label>Integer</label>
			<description>A grouped integer parameter.</description>
			<default>42</default>
		</parameter>

		<parameter name="requiredTextParameter" type="text" required="true">
			<label>Required Text</label>
			<description>A text parameter which is required.</description>
		</parameter>
		<parameter name="verifiedTextParameter" type="text" required="true">
			<label>Verified Text</label>
			<description>A text parameter which is required and must be verified by the user.</description>
			<verify>true</verify>
		</parameter>
		<parameter name="select_limited" type="text" required="false">
			<label>Select limited</label>
			<description>A select text parameter which is restricted to the given options.</description>
			<options>
				<option value="value1">Value 1</option>
				<option value="value2">Value 2</option>
				<option value="value3">Value 3</option>
			</options>
			<limitToOptions>true</limitToOptions>
			<default>value1</default>
		</parameter>
		<parameter name="select_variable" type="text" required="false">
			<label>Select variable</label>
			<description>A select text parameter without limit.</description>
			<options>
				<option value="value1">Value 1</option>
				<option value="value2">Value 2</option>
				<option value="value3">Value 3</option>
			</options>
			<limitToOptions>false</limitToOptions>
		</parameter>
		<parameter name="multiselect_integer_limit" type="integer" multiple="true">
			<label>Multiselect Integer - limit</label>
			<description>An integer parameter limited to </description>
			<multipleLimit>3</multipleLimit>
			<limitToOptions>true</limitToOptions>
			<options>
				<option value="1">One</option>
				<option value="2">Two</option>
				<option value="3">Three</option>
				<option value="4">Four</option>
				<option value="5">Five</option>
				<option value="6">Six</option>
				<option value="7">Seven</option>
				<option value="8">Eight</option>
				<option value="9">Nine</option>
				<option value="0">Zero</option>
			</options>
		</parameter>
		<parameter name="multiselect_text_limit" type="text" multiple="true">
			<label>Multiselect Text - limit</label>
			<description>An integer parameter limited to </description>
			<multipleLimit>3</multipleLimit>
			<limitToOptions>true</limitToOptions>
			<options>
				<option value="value1">One</option>
				<option value="value2">Two</option>
				<option value="value3">Three</option>
				<option value="value4">Four</option>
				<option value="value5">Five</option>
				<option value="value6">Six</option>
				<option value="value7">Seven</option>
				<option value="value8">Eight</option>
				<option value="value9">Nine</option>
				<option value="value0">Zero</option>
			</options>
		</parameter>
		<parameter name="select_decimal_limit" type="decimal">
			<label>Select Decimal - options from backend</label>
			<description>A decimal parameter with options provided by the backend.</description>
			<limitToOptions>true</limitToOptions>
			<!-- options are retrieved from org.eclipse.smarthome.binding.magic.internal.MagicServiceImpl. -->
		</parameter>
	</config-description>

</config-description:config-descriptions>

=== openhab/openhab-core/bundles/org.openhab.core.storage.json/ESH-INF/config/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config-description:config-descriptions
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:config-description="http://eclipse.org/smarthome/schemas/config-description/v1.0.0"
	xsi:schemaLocation="http://eclipse.org/smarthome/schemas/config-description/v1.0.0
		http://eclipse.org/smarthome/schemas/config-description-1.0.0.xsd">

	<config-description uri="system:json_storage">
		<parameter name="backup_files" type="integer" min="0" max="100">
			<label>Backup files</label>
			<description>Sets the number of backup files to keep.</description>
			<default>5</default>
		</parameter>
		<parameter name="write_delay" type="integer" min="0" max="60000">
			<label>Write delay</label>
			<description>Sets the time to wait before writing changes to disk. This can reduce the number of writes when many changes are being introduced within a short period. Time is defined in milliseconds.</description>
			<default>500</default>
		</parameter>
		<parameter name="max_defer_delay" type="integer" min="1000" max="60000">
			<label>Maximum write delay</label>
			<description>Sets the maximum period the service will wait to write data to disk in the event that many changes are happening continually.</description>
			<default>30000</default>
		</parameter>
	</config-description>

</config-description:config-descriptions>

=== openhab/openhab-core/bundles/org.openhab.core.thing/src/main/resources/OH-INF/config/hyteresisProfile.xml
<?xml version="1.0" encoding="UTF-8"?>
<config-description:config-descriptions
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:config-description="https://openhab.org/schemas/config-description/v1.0.0"
	xsi:schemaLocation="https://openhab.org/schemas/config-description/v1.0.0 https://openhab.org/schemas/config-description-1.0.0.xsd">

	<config-description uri="profile:system:hysteresis">
		<parameter name="lower" type="decimal" required="true">
			<label>Lower Bound</label>
			<description>Maps to ON if value is below lower bound.</description>
		</parameter>
		<parameter name="upper" type="decimal">
			<label>Upper Bound</label>
			<description>Maps to OFF if value is above upper bound.</description>
		</parameter>
	</config-description>
</config-description:config-descriptions>

=== openhab/openhab-core/bundles/org.openhab.core.model.script/resources/OH-INF/config/hli.xml
<?xml version="1.0" encoding="UTF-8"?>
<config-description:config-descriptions
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:config-description="https://openhab.org/schemas/config-description/v1.0.0"
	xsi:schemaLocation="https://openhab.org/schemas/config-description/v1.0.0
		https://openhab.org/schemas/config-description-1.0.0.xsd">

	<config-description uri="voice:rulehli">
		<parameter name="item" type="text">
			<context>item</context>
			<filter><criteria name="type">String</criteria></filter>
			<label>Voice Command Item</label>
			<description>The String Item to pass voice commands to.</description>
			<default>VoiceCommand</default>
		</parameter>
	</config-description>

</config-description:config-descriptions>

=== openhab/openhab-core/bundles/org.openhab.core/src/main/resources/OH-INF/config/i18n.xml
<?xml version="1.0" encoding="UTF-8"?>
<config-description:config-descriptions
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:config-description="https://openhab.org/schemas/config-description/v1.0.0"
	xsi:schemaLocation="https://openhab.org/schemas/config-description/v1.0.0
	https://openhab.org/schemas/config-description-1.0.0.xsd">

	<config-description uri="system:i18n">
		<parameter name="language" type="text">
			<label>Language</label>
			<description>The default language that should be used. If not specified, the system default locale is used.</description>
		</parameter>
		<parameter name="script" type="text">
			<label>Script</label>
			<description>The script that should be used.</description>
			<advanced>true</advanced>
		</parameter>
		<parameter name="region" type="text">
			<label>Country / Region</label>
			<description>The region that should be used.</description>
		</parameter>
		<parameter name="variant" type="text">
			<label>Variant</label>
			<description>A variation of the Locale. Any arbitrary value used to indicate a variation of a Locale.</description>
			<advanced>true</advanced>
		</parameter>
		<parameter name="timezone" type="text">
			<label>Time Zone</label>
			<description>A time zone can be set from the user interface. The underlying system's time zone is the default.</description>
		</parameter>
		<parameter name="location" type="text">
			<context>location</context>
			<label>Location</label>
			<description><![CDATA[The location of this installation.<br>Coordinates as &lt;latitude&gt;,&lt;longitude&gt;[&lt;altitude&gt;]<br>Example: "52.5200066,13.4049540" (Berlin)]]></description>
		</parameter>
		<parameter name="measurementSystem" type="text">
			<label>Measurement System</label>
			<description>The measurement system is used for unit conversion.</description>
			<advanced>true</advanced>
			<options>
				<option value="SI">Metric</option>
				<option value="US">Imperial (US)</option>
			</options>
		</parameter>
	</config-description>

</config-description:config-descriptions>

=== openhab/openhab-core/bundles/org.openhab.core.thing/src/main/resources/ESH-INF/config/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config-description:config-descriptions
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:config-description="https://openhab.org/schemas/config-description/v1.0.0"
	xsi:schemaLocation="https://openhab.org/schemas/config-description/v1.0.0
	https://openhab.org/schemas/config-description-1.0.0.xsd">

	<config-description uri="system:links">
		<parameter name="autoLinks" type="boolean" required="true">
			<label>Simple Mode</label>
			<description><![CDATA[
				<p>In simple mode, links and their according items are automatically created for new Things.</p>
				<p>If the simple mode is turned off, the user has the full control about which items channels are linked to. Existing links will remain untouched.</p>
			]]>
			</description>
			<default>true</default>
		</parameter>
	</config-description>

	<config-description uri="system:firmware-status-info-job">
		<parameter name="period" type="integer" min="1" required="true">
			<label>Period</label>
			<description>The period between successive firmware status info job execution.</description>
		</parameter>
		<parameter name="delay" type="integer" min="0" required="true">
			<label>Delay</label>
			<description>The time to delay the first firmware status info job execution.</description>
		</parameter>
		<parameter name="timeUnit" type="text" required="true">
			<label>Time unit</label>
			<description>The time unit of the firmware status info job execution.</description>
			<options>
				<option value="SECONDS">Seconds</option>
				<option value="MINUTES">Minutes</option>
				<option value="HOURS">Hours</option>
				<option value="DAYS">Days</option>
			</options>
		</parameter>
	</config-description>

</config-description:config-descriptions>

=== openhab/openhab-core/bundles/org.openhab.core.addon.marketplace/src/main/resources/OH-INF/config/marketplace.xml
<?xml version="1.0" encoding="UTF-8"?>
<config-description:config-descriptions
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:config-description="https://openhab.org/schemas/config-description/v1.0.0"
	xsi:schemaLocation="https://openhab.org/schemas/config-description/v1.0.0
		https://openhab.org/schemas/config-description-1.0.0.xsd">

	<config-description uri="system:marketplace">
		<parameter name="showUnpublished" type="boolean">
			<label>Show Unpublished Entries</label>
			<default>false</default>
			<description>Include entries which have not been tagged as published. Warning: this may include entries that are not
				ready and might not work or harm your installation. Enable at your own risk, for testing purposes only.</description>
		</parameter>
		<parameter name="apiKey" type="text">
			<advanced>true</advanced>
			<label>API Key for community.openhab.org</label>
			<description>Specify the API key to use on the community forum (for staff and curators - this allows for instance to
				see content which is not yet reviewed or otherwise hidden from the general public). Leave blank if you don't have
				one.</description>
		</parameter>
	</config-description>

	<config-description uri="system:jsonaddonservice">
		<parameter name="urls" type="text">
			<label>Add-on Service URLs</label>
			<description>Pipe (|) separated list of URLS that provide 3rd party add-on services via Json files. Warning: Bundles
				distributed over 3rd party addon services may lack proper review and can potentially contain malicious code and thus
				harm your system.</description>
		</parameter>
		<parameter name="showUnstable" type="boolean">
			<label>Show Non-Stable Bundles</label>
			<default>false</default>
			<description>Include entries which have not been tagged as "stable". These bundles should be used for testing
				purposes only and are not considered production-system ready.</description>
		</parameter>
	</config-description>

</config-description:config-descriptions>

=== openhab/openhab-core/bundles/org.openhab.core.audio/src/main/resources/ESH-INF/config/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config-description:config-descriptions
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:config-description="http://eclipse.org/smarthome/schemas/config-description/v1.0.0"
	xsi:schemaLocation="http://eclipse.org/smarthome/schemas/config-description/v1.0.0
		http://eclipse.org/smarthome/schemas/config-description-1.0.0.xsd">

	<config-description uri="system:audio">
		<parameter name="defaultSource" type="text" required="false">
			<label>Default Source</label>
			<description>The default audio source to use if no other is specified.</description>
		</parameter>
		<parameter name="defaultSink" type="text" required="false">
			<label>Default Sink</label>
			<description>The default audio sink to use if no other is specified.</description>
		</parameter>
	</config-description>

</config-description:config-descriptions>
