=== openhab/openhab-core/bundles/org.openhab.core.config.core/schema/config-description-1.0.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:config-description="https://openhab.org/schemas/config-description/v1.0.0"
	targetNamespace="https://openhab.org/schemas/config-description/v1.0.0">

	<xs:element name="config-descriptions">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="config-description" type="config-description:configDescription" minOccurs="1"
					maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="config-description" type="config-description:configDescription"/>

	<xs:simpleType name="idRestrictionPattern">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Za-z0-9\-_]+"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="uriRestrictionPattern">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Za-z0-9\-_]+(:[A-Za-z0-9\-_]+){1,2}"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="configDescription">
		<xs:sequence>
			<xs:element name="parameter-group" type="config-description:parameterGroup" minOccurs="0"
				maxOccurs="unbounded"/>
			<xs:element name="parameter" type="config-description:parameter" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="uri" type="config-description:uriRestrictionPattern" use="optional"/>
	</xs:complexType>

	<xs:complexType name="parameter">
		<xs:all>
			<xs:element name="context" type="config-description:contextType" minOccurs="0"/>
			<!-- deprecated element "required" -->
			<xs:element name="required" type="xs:boolean" default="false" minOccurs="0"/>
			<xs:element name="default" type="xs:string" minOccurs="0"/>
			<xs:element name="label" type="xs:string" minOccurs="0"/>
			<xs:element name="description" type="xs:string" minOccurs="0"/>
			<xs:element name="options" type="config-description:optionsType" minOccurs="0"/>
			<xs:element name="limitToOptions" type="xs:boolean" minOccurs="0"/>
			<xs:element name="filter" type="config-description:filterType" minOccurs="0"/>
			<xs:element name="advanced" type="xs:boolean" minOccurs="0"/>
			<xs:element name="verify" type="xs:boolean" minOccurs="0"/>
			<xs:element name="multipleLimit" type="xs:integer" minOccurs="0"/>
			<xs:element name="unitLabel" type="xs:string" minOccurs="0"/>
		</xs:all>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="type" type="config-description:parameterType" use="required"/>
		<xs:attribute name="groupName" type="xs:string"/>
		<xs:attribute name="min" type="xs:decimal"/>
		<xs:attribute name="max" type="xs:decimal"/>
		<xs:attribute name="step" type="xs:decimal"/>
		<xs:attribute name="pattern" type="xs:string"/>
		<xs:attribute name="required" type="xs:boolean"/>
		<xs:attribute name="readOnly" type="xs:boolean"/>
		<xs:attribute name="multiple" type="xs:boolean"/>
		<xs:attribute name="unit" type="config-description:unitType"/>
		<xs:attribute name="dynamic" type="xs:boolean"/>
	</xs:complexType>

	<xs:complexType name="parameterGroup">
		<xs:all>
			<xs:element name="label" type="xs:string" minOccurs="0"/>
			<xs:element name="description" type="xs:string" minOccurs="0"/>
			<xs:element name="context" type="config-description:contextType" minOccurs="0"/>
			<xs:element name="advanced" type="xs:boolean" minOccurs="0"/>
		</xs:all>
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="optionsType">
		<xs:sequence>
			<xs:element name="option" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="value" type="xs:string" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="filterType">
		<xs:sequence>
			<xs:element name="criteria" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="name" type="xs:string" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="parameterType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="text"/>
			<xs:enumeration value="integer"/>
			<xs:enumeration value="decimal"/>
			<xs:enumeration value="boolean"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="unitType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="A"/>
			<xs:enumeration value="cd"/>
			<xs:enumeration value="K"/>
			<xs:enumeration value="kg"/>
			<xs:enumeration value="m"/>
			<xs:enumeration value="mol"/>
			<xs:enumeration value="s"/>
			<xs:enumeration value="Bq"/>
			<xs:enumeration value="C"/>
			<xs:enumeration value="F"/>
			<xs:enumeration value="Gy"/>
			<xs:enumeration value="H"/>
			<xs:enumeration value="Hz"/>
			<xs:enumeration value="J"/>
			<xs:enumeration value="kat"/>
			<xs:enumeration value="lm"/>
			<xs:enumeration value="lx"/>
			<xs:enumeration value="N"/>
			<xs:enumeration value="Pa"/>
			<xs:enumeration value="rad"/>
			<xs:enumeration value="S"/>
			<xs:enumeration value="sr"/>
			<xs:enumeration value="Sv"/>
			<xs:enumeration value="T"/>
			<xs:enumeration value="V"/>
			<xs:enumeration value="W"/>
			<xs:enumeration value="Wb"/>
			<xs:enumeration value="Cel"/>
			<xs:enumeration value="Ω"/>
			<xs:enumeration value="g"/>
			<xs:enumeration value="m/s2"/>
			<xs:enumeration value="m2v"/>
			<xs:enumeration value="m3"/>
			<xs:enumeration value="kph"/>
			<xs:enumeration value="%"/>
			<xs:enumeration value="l"/>
			<xs:enumeration value="ms"/>
			<xs:enumeration value="min"/>
			<xs:enumeration value="h"/>
			<xs:enumeration value="d"/>
			<xs:enumeration value="week"/>
			<xs:enumeration value="y"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="configDescriptionRef">
		<xs:attribute name="uri" type="config-description:uriRestrictionPattern" use="required"/>
	</xs:complexType>

	<xs:simpleType name="contextType">
		<xs:union>
			<xs:simpleType>
				<!-- old behavior: allow any non empty string -->
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
				</xs:restriction>
			</xs:simpleType>
			<xs:simpleType>
				<!-- enhanced behavior: allow "special meaning" options (so IDE can suggest them) -->
				<xs:restriction base="xs:string">
					<xs:enumeration value="channel"/>
					<xs:enumeration value="channel-type"/>
					<xs:enumeration value="color"/>
					<xs:enumeration value="cronexpression"/>
					<xs:enumeration value="date"/>
					<xs:enumeration value="datetime"/>
					<xs:enumeration value="dayOfWeek"/>
					<xs:enumeration value="email"/>
					<xs:enumeration value="group"/>
					<xs:enumeration value="item"/>
					<xs:enumeration value="location"/>
					<xs:enumeration value="mac-address"/>
					<xs:enumeration value="month"/>
					<xs:enumeration value="network-address"/>
					<xs:enumeration value="network-interface"/>
					<xs:enumeration value="page"/>
					<xs:enumeration value="password"/>
					<xs:enumeration value="password-create"/>
					<xs:enumeration value="persistence-service"/>
					<xs:enumeration value="props"/>
					<xs:enumeration value="qrcode"/>
					<xs:enumeration value="rule"/>
					<xs:enumeration value="script"/>
					<xs:enumeration value="serial-port"/>
					<xs:enumeration value="service"/>
					<xs:enumeration value="tag"/>
					<xs:enumeration value="telephone"/>
					<xs:enumeration value="thing"/>
					<xs:enumeration value="time"/>
					<xs:enumeration value="url"/>
					<xs:enumeration value="week"/>
					<xs:enumeration value="widget"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:union>
	</xs:simpleType>

</xs:schema>

=== openhab/openhab-core/bundles/org.openhab.nlp/src/main/resources/ESH-INF/config/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config-description:config-descriptions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:config-description="http://eclipse.org/smarthome/schemas/config-description/v1.0.0"
	xsi:schemaLocation="http://eclipse.org/smarthome/schemas/config-description/v1.0.0 http://eclipse.org/smarthome/schemas/config-description-1.0.0.xsd">

	<config-description uri="voice:opennlphli">
		<parameter name="theme" type="text" required="true">
			<label>Tokenizer</label>
			<description>The alphanumeric tokenizer removes punctuation and might help with languages where entities might not always be enclosed between whitespaces (French, Spanish, Italian... Example: "l'humidit√©", "l'alarme")</description>
			<options>
				<option value="whitespace">Whitespace</option>
				<option value="alphanumeric">Alphanumeric</option>
			</options>
			<default>whitespace</default>
		</parameter>
	</config-description>

</config-description:config-descriptions>

=== openhab/openhab-core/bundles/org.openhab.core.thing/src/main/resources/OH-INF/config/hysteresisProfile.xml
<?xml version="1.0" encoding="UTF-8"?>
<config-description:config-descriptions
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:config-description="https://openhab.org/schemas/config-description/v1.0.0"
	xsi:schemaLocation="https://openhab.org/schemas/config-description/v1.0.0 https://openhab.org/schemas/config-description-1.0.0.xsd">

	<config-description uri="profile:system:hysteresis">
		<parameter name="lower" type="text" required="true">
			<label>Lower Bound</label>
			<description>Maps to OFF if value is less than or equal to lower bound (plain number or number with unit).</description>
		</parameter>
		<parameter name="upper" type="text">
			<label>Upper Bound</label>
			<description>Maps to ON if value is greater than or equal to upper bound (plain number or number with unit).</description>
		</parameter>
		<parameter name="inverted" type="boolean">
			<label>Inverted</label>
			<description>Inverts resulting mapping of ON / OFF, if true.</description>
			<default>false</default>
		</parameter>
		<parameter name="excludeItemState" type="boolean">
			<label>Exclude Item State</label>
			<description>Do not include Item State in comparison.</description>
			<default>false</default>
		</parameter>
	</config-description>
</config-description:config-descriptions>

=== openhab/openhab-core/bundles/org.openhab.core.thing/src/main/resources/ESH-INF/config/roundProfile.xml
<?xml version="1.0" encoding="UTF-8"?>
<config-description:config-descriptions
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:config-description="https://openhab.org/schemas/config-description/v1.0.0"
	xsi:schemaLocation="https://openhab.org/schemas/config-description/v1.0.0 https://openhab.org/schemas/config-description-1.0.0.xsd">

	<config-description uri="profile:system:round">
		<parameter name="scale" type="integer" min="0" max="16" required="true">
			<label>Scale</label>
			<description>Scale (non-negative number) to be applied on the state.</description>
		</parameter>
		<parameter name="mode" type="text">
			<label>Rounding Mode</label>
			<description>Rounding mode to be used (UP, DOWN, CEILING, FLOOR, HALF_UP or HALF_DOWN). Default: HALF_UP.</description>
			<default>HALF_UP</default>
			<options>
				<option value="UP">UP</option>
				<option value="DOWN">DOWN</option>
				<option value="CEILING">CEILING</option>
				<option value="FLOOR">FLOOR</option>
				<option value="HALF_UP">HALF_UP</option>
				<option value="HALF_DOWN">HALF_DOWN</option>
			</options>
		</parameter>
	</config-description>
</config-description:config-descriptions>

=== openhab/openhab-core/bundles/org.openhab.core.voice/src/main/resources/ESH-INF/config/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config-description:config-descriptions
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:config-description="http://eclipse.org/smarthome/schemas/config-description/v1.0.0"
	xsi:schemaLocation="http://eclipse.org/smarthome/schemas/config-description/v1.0.0 http://eclipse.org/smarthome/schemas/config-description-1.0.0.xsd">

	<config-description uri="system:voice">
		<parameter name="defaultTTS" type="text" required="false">
			<label>Default Text-to-Speech</label>
			<description>The default text-to-speech service to use if no other is specified.</description>
		</parameter>
		<parameter name="defaultSTT" type="text" required="false">
			<label>Default Speech-to-Text</label>
			<description>The default speech-to-text service to use if no other is specified.</description>
		</parameter>
		<parameter name="defaultVoice" type="text" required="false">
			<label>Default Voice</label>
			<description>The default voice to use if no specific TTS service or voice is specified.</description>
		</parameter>
		<parameter name="defaultHLI" type="text" required="false">
			<label>Default Human Language Interpreter</label>
			<description>The default human language interpreter to use if no other is specified.</description>
		</parameter>
		<parameter name="defaultKS" type="text" required="false">
			<label>Default Keyword Spotter</label>
			<description>The default keyword spotting service to use if no other is specified.</description>
		</parameter>
		<parameter name="keyword" type="text" required="false">
			<label>Magic Word</label>
			<description>The magic word to spot before initiating a dialog.</description>
		</parameter>
		<parameter name="listeningItem" type="text" required="false">
			<context>item</context>
			<filter><criteria name="type">Switch</criteria></filter>
			<label>Listening switch</label>
			<description>If provided, the item will be switched on during the period when the dialog processor has spotted the keyword and is listening for commands.</description>
		</parameter>
	</config-description>

</config-description:config-descriptions>

=== openhab/openhab-core/bundles/org.openhab.core.ui.chart/src/main/resources/ESH-INF/config/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config-description:config-descriptions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:config-description="http://eclipse.org/smarthome/schemas/config-description/v1.0.0"
	xsi:schemaLocation="http://eclipse.org/smarthome/schemas/config-description/v1.0.0
	http://eclipse.org/smarthome/schemas/config-description-1.0.0.xsd">

	<config-description uri="system:chart">
		<parameter name="defaultHeight" type="integer" required="false">
			<label>Default Height</label>
			<description>Defines the default height in pixels for the chart to build.</description>
			<default>240</default>
		</parameter>
		<parameter name="defaultWidth" type="integer" required="false">
			<label>Default Width</label>
			<description>Defines the default width in pixels for the chart to build.</description>
			<default>480</default>
		</parameter>
		<parameter name="scale" type="decimal" required="false" min="0" step="0.1">
			<label>Scale</label>
			<description>Defines the scale to apply to the requested chart height (0.5 to divide by 2 for example).</description>
			<default>1</default>
			<advanced>true</advanced>
		</parameter>
		<parameter name="maxWidth" type="integer" required="false">
			<label>Maximum Width</label>
			<description>Defines the maximum width in pixels for the chart to build.</description>
			<advanced>true</advanced>
		</parameter>
	</config-description>

</config-description:config-descriptions>

=== openhab/openhab-core/bundles/org.openhab.core.voice/src/main/resources/OH-INF/config/voice.xml
<?xml version="1.0" encoding="UTF-8"?>
<config-description:config-descriptions
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:config-description="https://openhab.org/schemas/config-description/v1.0.0"
	xsi:schemaLocation="https://openhab.org/schemas/config-description/v1.0.0 https://openhab.org/schemas/config-description-1.0.0.xsd">

	<config-description uri="system:voice">
		<parameter name="defaultTTS" type="text">
			<label>Default Text-to-Speech</label>
			<description>The default text-to-speech service to use if no other is specified.</description>
		</parameter>
		<parameter name="defaultSTT" type="text">
			<label>Default Speech-to-Text</label>
			<description>The default speech-to-text service to use if no other is specified.</description>
		</parameter>
		<parameter name="defaultVoice" type="text">
			<label>Default Voice</label>
			<description>The default voice to use if no specific TTS service or voice is specified.</description>
		</parameter>
		<parameter name="defaultHLI" type="text">
			<label>Default Human Language Interpreter</label>
			<description>The default human language interpreter to use if no other is specified.</description>
		</parameter>
		<parameter name="defaultKS" type="text">
			<label>Default Keyword Spotter</label>
			<description>The default keyword spotting service to use if no other is specified.</description>
		</parameter>
		<parameter name="keyword" type="text">
			<label>Magic Word</label>
			<description>The magic word to spot before initiating a dialog.</description>
		</parameter>
		<parameter name="listeningItem" type="text">
			<context>item</context>
			<filter>
				<criteria name="type">Switch</criteria>
			</filter>
			<label>Listening Switch</label>
			<description>If provided, the item will be switched on during the period when the dialog processor has spotted the
				keyword and is listening for commands.</description>
		</parameter>
		<parameter name="listeningMelody" type="text">
			<options>
				<option value="Bb">Bb</option>
				<option value="F#">F#</option>
				<option value="E">E</option>
			</options>
			<limitToOptions>false</limitToOptions>
			<label>Listening Melody</label>
			<description>A melody to be played to advertise the user the dialog processing is going to start, leave empty to
				disable it. (Spaced separated list of notes. Example: "A O:100 A':50")</description>
		</parameter>
		<parameter name="enableCacheTTS" type="boolean">
			<label>Enable TTS caching</label>
			<description>true to allow TTS services to cache audio files on disk.</description>
			<default>true</default>
		</parameter>
		<parameter name="cacheSizeTTS" type="integer">
			<label>TTS Cache Size</label>
			<description>The limit size of the TTS cache (in kB).</description>
			<default>10240</default>
		</parameter>
		<parameter name="maxTextLengthCacheTTS" type="integer">
			<label>TTS Cache Maximum Text Length</label>
			<description>The maximum length of texts handled by the TTS cache (in character). If exceeded, will pass the text to
				the TTS without storing it. 0 for no limit.</description>
			<default>150</default>
		</parameter>
		<parameter name="conversationHistoryLimit" type="integer" min="5" step="5">
			<label>Conversation History Limit</label>
			<description>The maximum number of messages to keep in a conversation history.</description>
			<default>50</default>
		</parameter>
		<parameter name="implicitItemPermission" type="text">
			<label>Implicit Item Permission</label>
			<description>The default permission for Items. If NO_ACCESS, items are only accessible if explicitly granted in the
				Item's or its parents' metadata.</description>
			<default>READ_WRITE</default>
			<options>
				<option value="NO_ACCESS">No Access</option>
				<option value="READ_ONLY">Read Only</option>
				<option value="READ_WRITE">Read &amp; Write</option>
			</options>
		</parameter>
	</config-description>

</config-description:config-descriptions>

=== openhab/openhab-core/bundles/org.openhab.core.audio/src/main/resources/OH-INF/config/audio.xml
<?xml version="1.0" encoding="UTF-8"?>
<config-description:config-descriptions
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:config-description="https://openhab.org/schemas/config-description/v1.0.0"
	xsi:schemaLocation="https://openhab.org/schemas/config-description/v1.0.0
		https://openhab.org/schemas/config-description-1.0.0.xsd">

	<config-description uri="system:audio">
		<parameter name="defaultSource" type="text">
			<label>Default Source</label>
			<description>The default audio source to use if no other is specified.</description>
		</parameter>
		<parameter name="defaultSink" type="text">
			<label>Default Sink</label>
			<description>The default audio sink to use if no other is specified.</description>
		</parameter>
	</config-description>

</config-description:config-descriptions>

=== openhab/openhab-core/bundles/org.openhab.core.io.transport.mqtt/src/main/resources/ESH-INF/config/brokerConnectionInstance.xml
<?xml version="1.0" encoding="UTF-8"?>
<config-description:config-descriptions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:config-description="https://openhab.org/schemas/config-description/v1.0.0"
	xsi:schemaLocation="https://openhab.org/schemas/config-description/v1.0.0
	https://openhab.org/schemas/config-description-1.0.0.xsd">

	<config-description uri="mqtt:systemBrokerConnectionInstance">

		<parameter-group name="group_connection">
			<label>Connection</label>
			<description>A group of connection parameters.</description>
			<advanced>false</advanced>
		</parameter-group>
		<parameter-group name="group_message_params">
			<label>Message parameters</label>
			<advanced>true</advanced>
		</parameter-group>
		<parameter-group name="group_lastwill_params">
			<label>Last will</label>
			<description>All last-will parameters</description>
			<advanced>true</advanced>
		</parameter-group>

		<parameter name="name" type="text" required="false" groupName="group_connection">
			<label>Connection name</label>
			<description>A connection name helps to identify a broker connection. If nothing is set, an automatic name based on the host and port will be generated.</description>
			<default />
		</parameter>

		<parameter name="host" type="text" required="true" groupName="group_connection">
			<label>Broker host</label>
			<description>Hostname or IP of the broker</description>
			<default />
		</parameter>
		<parameter name="port" type="integer" required="false" groupName="group_connection">
			<label>Broker port</label>
			<description>A custom broker connection port. Leave empty to use the default Mqtt ports for secure or non-secure connections</description>
			<default />
			<advanced>true</advanced>
		</parameter>
		<parameter name="secure" type="boolean" required="true" groupName="group_connection">
			<label>Secure connection?</label>
			<description>A broker connection is either a non-secure tcp connection or a tls secure connection</description>
			<default>false</default>
		</parameter>

		<parameter name="username" type="text" required="false" groupName="group_connection">
			<label>Broker username</label>
			<description>Broker username</description>
			<default />
		</parameter>
		<parameter name="password" type="text" required="false" groupName="group_connection">
			<label>Broker password</label>
			<description>Broker password</description>
			<default />
			<context>password</context>
		</parameter>
		<parameter name="clientID" type="text" required="false" groupName="group_connection">
			<label>Client ID</label>
			<description>An optional client ID used for this connection</description>
			<default />
			<advanced>true</advanced>
		</parameter>
		<parameter name="keepAlive" type="integer" required="false" groupName="group_connection">
			<label>Keep-alive (sec)</label>
			<description>Keep-alive timer in seconds. A too frequent timer could conquest the network / spam the Mqtt server, a too low value might risk that a broken connection is detected very late.</description>
			<default>60</default>
			<advanced>true</advanced>
		</parameter>

		<parameter name="qos" type="integer" required="false" groupName="group_message_params">
			<label>Quality of service</label>
			<description>The Quality of Service (QoS) level is an agreement between sender and receiver of a message regarding the guarantees of delivering a message.</description>
			<limitToOptions>true</limitToOptions>
			<options>
				<option value="0">At most once (best effort delivery "fire and forget")</option>
				<option value="1">At least once (guaranteed that a message will be delivered at least once)</option>
				<option value="2">Exactly once (guarantees that each message is received only once by the counterpart)</option>
			</options>
			<default>0</default>
		</parameter>
		<parameter name="retainMessages" type="boolean" required="false" groupName="group_message_params">
			<label>Retain messages</label>
			<description>Messages send by this connection are retained</description>
			<default>false</default>
		</parameter>


		<parameter name="lwtTopic" type="text" required="false" groupName="group_lastwill_params">
			<label>Last will topic</label>
			<description>When the connection dies, the last will is performed by the Mqtt server. This is the last-will topic. It must be set to perform a last-will.</description>
			<default />
		</parameter>
		<parameter name="lwtMessage" type="text" required="false" groupName="group_lastwill_params">
			<label>Last will message</label>
			<description>When the connection dies, the last will is performed by the Mqtt server. This is the last-will message. Can be empty.</description>
			<default />
		</parameter>
		<parameter name="lwtQos" type="integer" required="false" groupName="group_lastwill_params">
			<label>Last will quality of service</label>
			<description>The Quality of Service (QoS) level is an agreement between sender and receiver of a message regarding the guarantees of delivering a message.</description>
			<limitToOptions>true</limitToOptions>
			<options>
				<option value="0">At most once (best effort delivery "fire and forget")</option>
				<option value="1">At least once (guaranteed that a message will be delivered at least once)</option>
				<option value="2">Exactly once (guarantees that each message is received only once by the counterpart)</option>
			</options>
			<default>0</default>
		</parameter>
		<parameter name="lwtRetain" type="boolean" required="false" groupName="group_lastwill_params">
			<label>Last will retain message</label>
			<description>When the connection dies, the last will is performed by the Mqtt server. If retain message is checked, the message will be retained by the Mqtt server.</description>
			<default>false</default>
		</parameter>
	</config-description>
</config-description:config-descriptions>
