=== openhab/openhab-core/bundles/org.openhab.core.config.core/schema/config-description-1.0.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:config-description="https://openhab.org/schemas/config-description/v1.0.0"
	targetNamespace="https://openhab.org/schemas/config-description/v1.0.0">

	<xs:element name="config-descriptions">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="config-description" type="config-description:configDescription" minOccurs="1"
					maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="config-description" type="config-description:configDescription"/>

	<xs:simpleType name="idRestrictionPattern">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Za-z0-9\-_]+"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="uriRestrictionPattern">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Za-z0-9\-_]+(:[A-Za-z0-9\-_]+){1,2}"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="configDescription">
		<xs:sequence>
			<xs:element name="parameter-group" type="config-description:parameterGroup" minOccurs="0"
				maxOccurs="unbounded"/>
			<xs:element name="parameter" type="config-description:parameter" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="uri" type="config-description:uriRestrictionPattern" use="optional"/>
	</xs:complexType>

	<xs:complexType name="parameter">
		<xs:all>
			<xs:element name="context" type="config-description:contextType" minOccurs="0"/>
			<!-- deprecated element "required" -->
			<xs:element name="required" type="xs:boolean" default="false" minOccurs="0"/>
			<xs:element name="default" type="xs:string" minOccurs="0"/>
			<xs:element name="label" type="xs:string" minOccurs="0"/>
			<xs:element name="description" type="xs:string" minOccurs="0"/>
			<xs:element name="options" type="config-description:optionsType" minOccurs="0"/>
			<xs:element name="limitToOptions" type="xs:boolean" minOccurs="0"/>
			<xs:element name="filter" type="config-description:filterType" minOccurs="0"/>
			<xs:element name="advanced" type="xs:boolean" minOccurs="0"/>
			<xs:element name="verify" type="xs:boolean" minOccurs="0"/>
			<xs:element name="multipleLimit" type="xs:integer" minOccurs="0"/>
			<xs:element name="unitLabel" type="xs:string" minOccurs="0"/>
		</xs:all>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="type" type="config-description:parameterType" use="required"/>
		<xs:attribute name="groupName" type="xs:string"/>
		<xs:attribute name="min" type="xs:decimal"/>
		<xs:attribute name="max" type="xs:decimal"/>
		<xs:attribute name="step" type="xs:decimal"/>
		<xs:attribute name="pattern" type="xs:string"/>
		<xs:attribute name="required" type="xs:boolean"/>
		<xs:attribute name="readOnly" type="xs:boolean"/>
		<xs:attribute name="multiple" type="xs:boolean"/>
		<xs:attribute name="unit" type="config-description:unitType"/>
		<xs:attribute name="dynamic" type="xs:boolean"/>
	</xs:complexType>

	<xs:complexType name="parameterGroup">
		<xs:all>
			<xs:element name="label" type="xs:string" minOccurs="0"/>
			<xs:element name="description" type="xs:string" minOccurs="0"/>
			<xs:element name="context" type="config-description:contextType" minOccurs="0"/>
			<xs:element name="advanced" type="xs:boolean" minOccurs="0"/>
		</xs:all>
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="optionsType">
		<xs:sequence>
			<xs:element name="option" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="value" type="xs:string" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="filterType">
		<xs:sequence>
			<xs:element name="criteria" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="name" type="xs:string" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="parameterType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="text"/>
			<xs:enumeration value="integer"/>
			<xs:enumeration value="decimal"/>
			<xs:enumeration value="boolean"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="unitType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="A"/>
			<xs:enumeration value="cd"/>
			<xs:enumeration value="K"/>
			<xs:enumeration value="kg"/>
			<xs:enumeration value="m"/>
			<xs:enumeration value="mol"/>
			<xs:enumeration value="s"/>
			<xs:enumeration value="Bq"/>
			<xs:enumeration value="C"/>
			<xs:enumeration value="F"/>
			<xs:enumeration value="Gy"/>
			<xs:enumeration value="H"/>
			<xs:enumeration value="Hz"/>
			<xs:enumeration value="J"/>
			<xs:enumeration value="kat"/>
			<xs:enumeration value="lm"/>
			<xs:enumeration value="lx"/>
			<xs:enumeration value="N"/>
			<xs:enumeration value="Pa"/>
			<xs:enumeration value="rad"/>
			<xs:enumeration value="S"/>
			<xs:enumeration value="sr"/>
			<xs:enumeration value="Sv"/>
			<xs:enumeration value="T"/>
			<xs:enumeration value="V"/>
			<xs:enumeration value="W"/>
			<xs:enumeration value="Wb"/>
			<xs:enumeration value="Cel"/>
			<xs:enumeration value="Ω"/>
			<xs:enumeration value="g"/>
			<xs:enumeration value="m/s2"/>
			<xs:enumeration value="m2v"/>
			<xs:enumeration value="m3"/>
			<xs:enumeration value="kph"/>
			<xs:enumeration value="%"/>
			<xs:enumeration value="l"/>
			<xs:enumeration value="ms"/>
			<xs:enumeration value="min"/>
			<xs:enumeration value="h"/>
			<xs:enumeration value="d"/>
			<xs:enumeration value="week"/>
			<xs:enumeration value="y"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="configDescriptionRef">
		<xs:attribute name="uri" type="config-description:uriRestrictionPattern" use="required"/>
	</xs:complexType>

	<xs:simpleType name="contextType">
		<xs:union>
			<xs:simpleType>
				<!-- old behavior: allow any non empty string -->
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
				</xs:restriction>
			</xs:simpleType>
			<xs:simpleType>
				<!-- enhanced behavior: allow "special meaning" options (so IDE can suggest them) -->
				<xs:restriction base="xs:string">
					<xs:enumeration value="channel"/>
					<xs:enumeration value="channel-type"/>
					<xs:enumeration value="color"/>
					<xs:enumeration value="cronexpression"/>
					<xs:enumeration value="date"/>
					<xs:enumeration value="datetime"/>
					<xs:enumeration value="dayOfWeek"/>
					<xs:enumeration value="email"/>
					<xs:enumeration value="group"/>
					<xs:enumeration value="item"/>
					<xs:enumeration value="location"/>
					<xs:enumeration value="mac-address"/>
					<xs:enumeration value="month"/>
					<xs:enumeration value="network-address"/>
					<xs:enumeration value="network-interface"/>
					<xs:enumeration value="page"/>
					<xs:enumeration value="password"/>
					<xs:enumeration value="password-create"/>
					<xs:enumeration value="persistence-service"/>
					<xs:enumeration value="props"/>
					<xs:enumeration value="qrcode"/>
					<xs:enumeration value="rule"/>
					<xs:enumeration value="script"/>
					<xs:enumeration value="serial-port"/>
					<xs:enumeration value="service"/>
					<xs:enumeration value="tag"/>
					<xs:enumeration value="telephone"/>
					<xs:enumeration value="thing"/>
					<xs:enumeration value="time"/>
					<xs:enumeration value="url"/>
					<xs:enumeration value="week"/>
					<xs:enumeration value="widget"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:union>
	</xs:simpleType>

</xs:schema>

=== openhab/openhab-core/bundles/org.openhab.core.config.discovery/src/main/resources/ESH-INF/config/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config-description:config-descriptions
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:config-description="https://openhab.org/schemas/config-description/v1.0.0"
	xsi:schemaLocation="https://openhab.org/schemas/config-description/v1.0.0
		https://openhab.org/schemas/config-description-1.0.0.xsd">

	<config-description uri="system:inbox">
		<parameter name="autoIgnore" type="boolean">
			<label>Auto Ignore</label>
			<description><![CDATA[
				<p>If enabled, an inbox result matching an existing thing is automatically ignored.</p>
				<p>If set to false, the inbox may contain results although identical things already exist.</p>
			]]>
			</description>
			<default>true</default>
		</parameter>
		<parameter name="autoApprove" type="boolean">
			<label>Auto Approve</label>
			<description>If enabled, inbox results are automatically approved, unless they were marked as ignored.</description>
			<default>false</default>
		</parameter>
	</config-description>

</config-description:config-descriptions>

=== openhab/openhab-core/bundles/org.openhab.core.automation.module.script/src/main/resources/OH-INF/config/script-profile.xml
<?xml version="1.0" encoding="UTF-8"?>
<config-description:config-descriptions
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:config-description="https://openhab.org/schemas/config-description/v1.0.0"
	xsi:schemaLocation="https://openhab.org/schemas/config-description/v1.0.0 https://openhab.org/schemas/config-description-1.0.0.xsd">

	<config-description uri="profile:system:script">
		<parameter name="toItemScript" type="text">
			<label>To Item Script</label>
			<description>The Script for transforming states and commands from handler to item.</description>
		</parameter>
		<parameter name="toHandlerScript" type="text">
			<label>To Handler Script</label>
			<description>The Script for transforming states and commands from item to handler.</description>
		</parameter>
	</config-description>

</config-description:config-descriptions>

=== openhab/openhab-core/bundles/org.openhab.core/src/main/resources/OH-INF/config/units.xml
<?xml version="1.0" encoding="UTF-8"?>
<config-description:config-descriptions
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:config-description="https://openhab.org/schemas/config-description/v1.0.0"
	xsi:schemaLocation="https://openhab.org/schemas/config-description/v1.0.0
	https://openhab.org/schemas/config-description-1.0.0.xsd">

	<config-description uri="system:units">

		<parameter name="currencyProvider" type="text">
			<label>Currency Provider</label>
			<description>The service that is used to provide a set of currencies and their exchange rates.</description>
		</parameter>
		<parameter name="fixedBaseCurrency" type="text" pattern="[A-Z]{3}">
			<label>Fixed Base Currency</label>
			<description>The base currency of this system when the fixed currency provider is used.</description>
		</parameter>

	</config-description>
</config-description:config-descriptions>

=== openhab/openhab-core/bundles/org.openhab.core/src/main/resources/ESH-INF/config/networkinterface.xml
<?xml version="1.0" encoding="UTF-8"?>
<config-description:config-descriptions
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:config-description="https://openhab.org/schemas/config-description/v1.0.0"
	xsi:schemaLocation="https://openhab.org/schemas/config-description/v1.0.0
	https://openhab.org/schemas/config-description-1.0.0.xsd">

	<config-description uri="system:network">
		<parameter name="primaryAddress" type="text">
			<label>Primary Address</label>
			<description>
				A subnet (e.g. 192.168.1.0/24) <!-- or an IP address (e.g. 192.168.1.5) -->
			</description>
			<limitToOptions>true</limitToOptions>
		</parameter>
		<parameter name="broadcastAddress" type="text">
			<label>Broadcast Address</label>
			<description>A broadcast address (e.g. 192.168.1.255)</description>
			<limitToOptions>true</limitToOptions>
			<advanced>true</advanced>
		</parameter>
		<parameter name="useOnlyOneAddress" type="boolean">
			<label>Single IP Address per Interface</label>
			<description>Use only one IP address per interface and family</description>
			<default>false</default>
			<advanced>true</advanced>
		</parameter>
		<parameter name="useIPv6" type="boolean">
			<label>Use IPv6</label>
			<description>Use IPv6 Addresses if available</description>
			<default>true</default>
			<advanced>true</advanced>
		</parameter>
	</config-description>

</config-description:config-descriptions>

=== openhab/openhab-core/tools/i18n-plugin/src/test/resources/acmeweather.bundle/OH-INF/config/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config-description:config-descriptions
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:config-description="https://openhab.org/schemas/config-description/v1.0.0"
	xsi:schemaLocation="https://openhab.org/schemas/config-description/v1.0.0 https://openhab.org/schemas/config-description-1.0.0.xsd">

	<config-description uri="thing-type:acmeweather:weather">
		<parameter name="refreshInterval" type="integer" min="1" unit="min">
			<label>Refresh Interval</label>
			<description>Specifies the refresh interval (in minutes).</description>
			<default>60</default>
		</parameter>
		<parameter name="language" type="text">
			<label>Language</label>
			<description>Language to be used by the ACME API.</description>
			<options>
				<option value="nl">Dutch</option>
				<option value="de DE">German (Germany)</option>
				<option value="de CH">German (Switzerland)</option>
				<option value="en">English</option>
				<option value="fr">French</option>
			</options>
		</parameter>
	</config-description>

</config-description:config-descriptions>

=== openhab/openhab-core/bundles/org.openhab.core.test.magic/src/main/resources/ESH-INF/config/magicMultiAction.xml
<?xml version="1.0" encoding="UTF-8"?>
<config-description:config-descriptions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:config-description="http://eclipse.org/smarthome/schemas/config-description/v1.0.0"
	xsi:schemaLocation="http://eclipse.org/smarthome/schemas/config-description/v1.0.0
	http://eclipse.org/smarthome/schemas/config-description-1.0.0.xsd">

	<config-description uri="automationAction:magicMultiAction">
		<parameter name="textParam" type="text">
			<label>text parameter</label>
			<description>Enter a text message.</description>
		</parameter>
		<parameter name="boolParam" type="boolean">
			<label>Enable parameter</label>
			<description>Enable this parameter.</description>
			<default>true</default>
			<advanced>true</advanced>
		</parameter>
	</config-description>

</config-description:config-descriptions>

=== openhab/openhab-core/bundles/org.openhab.core.io.rest.auth/src/main/resources/OH-INF/config/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config-description:config-descriptions
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:config-description="https://openhab.org/schemas/config-description/v1.0.0"
	xsi:schemaLocation="https://openhab.org/schemas/config-description/v1.0.0 https://openhab.org/schemas/config-description-1.0.0.xsd">

	<config-description uri="system:restauth">
		<parameter name="allowBasicAuth" type="boolean" required="false">
			<label>Allow Basic Authentication</label>
			<default>false</default>
			<description>Allow the use of Basic authentication to access protected API resources, in addition to access tokens
				and API tokens.</description>
		</parameter>
		<parameter name="cacheExpiration" type="integer">
			<advanced>true</advanced>
			<label>Cache Expiration Time</label>
			<default>6</default>
			<unitLabel>h</unitLabel>
			<description>When basic authentication is activated, credentials are put in a cache in order to speed up request
				authorization.
				The entries in the cache expire after a while in order to not keep credentials in memory indefinitely.
				This value defines the expiration time in hours.
			</description>
		</parameter>
		<parameter name="implicitUserRole" type="boolean" required="false">
			<advanced>true</advanced>
			<label>Implicit user role for unauthenticated requests</label>
			<default>true</default>
			<description>By default, operations requiring the "user" role are available when unauthenticated. Disabling this
				option will enforce authorization for these operations. Warning: This causes clients that do not
				support
				authentication to break.</description>
		</parameter>
	</config-description>

</config-description:config-descriptions>

=== openhab/openhab-core/bundles/org.openhab.core.thing/src/main/resources/OH-INF/config/timestampOffsetProfile.xml
<?xml version="1.0" encoding="UTF-8"?>
<config-description:config-descriptions
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:config-description="https://openhab.org/schemas/config-description/v1.0.0"
	xsi:schemaLocation="https://openhab.org/schemas/config-description/v1.0.0
	https://openhab.org/schemas/config-description-1.0.0.xsd">

	<config-description uri="profile:system:timestamp-offset">
		<parameter name="offset" type="integer" required="true" unit="s">
			<label>Offset</label>
			<description>Offset to be applied on the state towards the item. The negative offset will be applied
				in the reverse
				direction.</description>
		</parameter>
		<parameter name="timezone" type="text">
			<label>Time Zone</label>
			<description>A time zone to be applied on the state towards the item.</description>
			<advanced>true</advanced>
		</parameter>
	</config-description>
</config-description:config-descriptions>
