=== openhab/openhab-core/bundles/org.openhab.core.addon/schema/suggested-addon-candidates-1.0.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:suggested-addon-candidates="https://openhab.org/schemas/suggested-addon-candidates/v1.0.0"
	targetNamespace="https://openhab.org/schemas/suggested-addon-candidates/v1.0.0">

	<xs:element name="suggested-addon-candidates">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="candidate" maxOccurs="unbounded"
					minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="addon-uid" />
							<xs:element name="discovery-method"
								maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:string" name="service-type" />
										<xs:element name="match-property"
											maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element type="xs:string" name="name" />
													<xs:element type="xs:string" name="regex" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string"
											name="mdns-service-type" minOccurs="0" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== openhab/openhab-core/bundles/org.openhab.core.config.discovery.addon/src/main/resources/suggested-addon-candidates.xml
<?xml version="1.0" encoding="UTF-8"?>
<suggested-addon-candidates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:suggested-addon-candidates="https://openhab.org/schemas/suggested-addon-candidates/v1.0.0"
	xsi:schemaLocation="https://openhab.org/schemas/suggested-addon-candidates/v1.0.0 https://openhab.org/schemas/suggested-addon-candidates-1.0.0.xsd">

	<candidate>
		<addon-uid>binding.hpprinter</addon-uid>
		<discovery-method>
			<service-type>mdns</service-type>
			<match-property>
				<name>rp</name>
				<regex>.*</regex>
			</match-property>
			<match-property>
				<name>ty</name>
				<regex>hp (.*)</regex>
			</match-property>
			<mdns-service-type>_printer._tcp.local.</mdns-service-type>
		</discovery-method>
	</candidate>
	<candidate>
		<addon-uid>binding.hue</addon-uid>
		<discovery-method>
			<service-type>upnp</service-type>
			<match-property>
				<name>modelName</name>
				<regex>Philips hue bridge</regex>
			</match-property>
		</discovery-method>
		<discovery-method>
			<service-type>mdns</service-type>
			<mdns-service-type>_hue._tcp.local.</mdns-service-type>
		</discovery-method>
	</candidate>
</suggested-addon-candidates>
