=== openhab/openhab-core/bundles/org.openhab.core.thing.xml/thing-description-1.0.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
        xmlns:thing-description="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0"
        xmlns:config-description="http://eclipse.org/smarthome/schemas/config-description/v1.0.0"
        targetNamespace="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0">

    <xs:import namespace="http://eclipse.org/smarthome/schemas/config-description/v1.0.0"
            schemaLocation="http://eclipse.org/smarthome/schemas/config-description-1.0.0.xsd"/>

    <xs:element name="thing-descriptions">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element name="thing-type" type="thing-description:thingType"/>
                <xs:element name="bridge-type" type="thing-description:bridgeType"/>
                <xs:element name="channel-type" type="thing-description:channelType"/>
                <xs:element name="channel-group-type" type="thing-description:channelGroupType"/>
            </xs:choice>
            <xs:attribute name="bindingId" type="config-description:idRestrictionPattern" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="thingType">
        <xs:sequence>
            <xs:element name="supported-bridge-type-refs" type="thing-description:supportedBridgeTypeRefs" minOccurs="0"/>
            <xs:element name="label" type="xs:string"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
            <xs:element name="category" type="xs:string" minOccurs="0"/>
            <xs:choice minOccurs="0">
                <xs:element name="channels" type="thing-description:channels"/>
                <xs:element name="channel-groups" type="thing-description:channelGroups"/>
            </xs:choice>
            <xs:element name="properties" type="thing-description:properties" minOccurs="0"/>
            <xs:element name="representation-property" type="xs:string" minOccurs="0"/>
            <xs:choice minOccurs="0">
                <xs:element name="config-description" type="config-description:configDescription"/>
                <xs:element name="config-description-ref" type="config-description:configDescriptionRef"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="id" type="config-description:idRestrictionPattern" use="required"/>
        <xs:attribute name="listed" type="xs:boolean" default="true" use="optional"/>
        <xs:attribute name="extensible" type="thing-description:namespaceIdListRestrictionPattern" use="optional"/>
    </xs:complexType>
    
    <xs:simpleType name="namespaceIdListRestrictionPattern">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z0-9\-_.]+(,( )?[A-Za-z0-9\-_.]+)*" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="bridgeType">
        <xs:complexContent>
            <xs:extension base="thing-description:thingType"/>
        </xs:complexContent>
    </xs:complexType>

    <xs:simpleType name="auto-update-policy">
        <xs:restriction base="xs:string">
            <xs:enumeration value="veto" />
            <xs:enumeration value="default" />
            <xs:enumeration value="recommend" />
        </xs:restriction>
    </xs:simpleType>    

    <xs:complexType name="channelType">
        <xs:sequence>
            <xs:element name="item-type" type="xs:string" minOccurs="0"/>
            <xs:element name="kind" type="xs:string" minOccurs="0"/>
            <xs:element name="label" type="xs:string"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
            <xs:element name="category" type="xs:string" minOccurs="0"/>
            <xs:element name="tags" type="thing-description:tags" minOccurs="0"/>
            <xs:element name="state" type="thing-description:state" minOccurs="0"/>
            <xs:element name="command" type="thing-description:command" minOccurs="0"/>
            <xs:element name="event" type="thing-description:event" minOccurs="0"/>
            <xs:element name="autoUpdatePolicy" type="thing-description:auto-update-policy" minOccurs="0"/>
            <xs:choice minOccurs="0">
                <xs:element name="config-description" type="config-description:configDescription"/>
                <xs:element name="config-description-ref" type="config-description:configDescriptionRef"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="id" type="config-description:idRestrictionPattern" use="required"/>
        <xs:attribute name="advanced" type="xs:boolean" default="false" use="optional"/>
        <xs:attribute name="system" type="xs:boolean" default="false" use="optional"/>
    </xs:complexType>

    <xs:complexType name="channelGroupType">
        <xs:sequence>
            <xs:element name="label" type="xs:string"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
            <xs:element name="category" type="xs:string" minOccurs="0"/>
            <xs:element name="channels" type="thing-description:channels" minOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="id" type="config-description:idRestrictionPattern" use="required"/>
        <xs:attribute name="advanced" type="xs:boolean" default="false" use="optional"/>
    </xs:complexType>

    <xs:complexType name="supportedBridgeTypeRefs">
        <xs:sequence>
            <xs:element name="bridge-type-ref" type="thing-description:bridgeTypeRef" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="bridgeTypeRef">
        <xs:attribute name="id" type="config-description:idRestrictionPattern" use="required"/>
    </xs:complexType>

    <xs:complexType name="channels">
        <xs:sequence>
            <xs:element name="channel" type="thing-description:channel" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="namespaceIdRestrictionPattern">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z0-9\-_.]+" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="channel">
        <xs:sequence>
            <xs:element name="label" type="xs:string" minOccurs="0"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
            <xs:element name="properties" type="thing-description:properties" minOccurs="0"/>
            <xs:element name="autoUpdatePolicy" type="thing-description:auto-update-policy" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="id" type="config-description:idRestrictionPattern" use="required"/>
        <xs:attribute name="typeId" type="thing-description:namespaceIdRestrictionPattern" use="required"/>
    </xs:complexType>

    <xs:complexType name="channelGroups">
        <xs:sequence>
            <xs:element name="channel-group" type="thing-description:channelGroup" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="channelGroup">
        <xs:sequence>
            <xs:element name="label" type="xs:string" minOccurs="0"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="id" type="config-description:idRestrictionPattern" use="required"/>
        <xs:attribute name="typeId" type="config-description:idRestrictionPattern" use="required"/>
    </xs:complexType>

    <xs:complexType name="tags">
        <xs:sequence>
            <xs:element name="tag" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="state">
        <xs:sequence>
            <xs:element name="options" type="thing-description:options" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="min" type="xs:decimal" use="optional"/>
        <xs:attribute name="max" type="xs:decimal" use="optional"/>
        <xs:attribute name="step" type="xs:decimal" use="optional"/>
        <xs:attribute name="pattern" type="xs:string" use="optional"/>
        <xs:attribute name="readOnly" type="xs:boolean" default="false" use="optional"/>
    </xs:complexType>

    <xs:complexType name="event">
        <xs:sequence>
            <xs:element name="options" type="thing-description:options" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="options">
        <xs:sequence>
            <xs:element name="option" type="thing-description:option" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="command">
        <xs:sequence>
            <xs:element name="options" type="thing-description:options" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="option">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="value" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

	<xs:complexType name="properties">
		<xs:sequence>
			<xs:element name="property" type="thing-description:property" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="property">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="name" type="xs:string" use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:simpleType name="dimension">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Intensity" />
			<xs:enumeration value="Acceleration" />
			<xs:enumeration value="AmountOfSubstance" />
			<xs:enumeration value="Angle" />
			<xs:enumeration value="AngularAcceleration" />
			<xs:enumeration value="AngularVelocity" />
			<xs:enumeration value="Area" />
			<xs:enumeration value="CatalyticActivity" />
			<xs:enumeration value="DataAmount" />
			<xs:enumeration value="DataRate" />
			<xs:enumeration value="Dimensionless" />
			<xs:enumeration value="Duration" />
			<xs:enumeration value="DynamicViscosity" />
			<xs:enumeration value="ElectricCapacitance" />
			<xs:enumeration value="ElectricCharge" />
			<xs:enumeration value="ElectricConductance" />
			<xs:enumeration value="ElectricCurrent" />
			<xs:enumeration value="ElectricInductance" />
			<xs:enumeration value="ElectricPotential" />
			<xs:enumeration value="ElectricResistance" />
			<xs:enumeration value="Energy" />
			<xs:enumeration value="Force" />
			<xs:enumeration value="Frequency" />
			<xs:enumeration value="Illuminance" />
			<xs:enumeration value="KinematicViscosity" />
			<xs:enumeration value="Length" />
			<xs:enumeration value="LuminousFlux" />
			<xs:enumeration value="LuminousIntensity" />
			<xs:enumeration value="MagneticFlux" />
			<xs:enumeration value="MagneticFluxDensity" />
			<xs:enumeration value="Mass" />
			<xs:enumeration value="MassFlowRate" />
			<xs:enumeration value="Power" />
			<xs:enumeration value="Pressure" />
			<xs:enumeration value="RadiationDoseAbsorbed" />
			<xs:enumeration value="RadiationDoseEffective" />
			<xs:enumeration value="RadioactiveActivity" />
			<xs:enumeration value="SolidAngle" />
			<xs:enumeration value="Speed" />
			<xs:enumeration value="Temperature" />
			<xs:enumeration value="Torque" />
			<xs:enumeration value="Velocity" />
			<xs:enumeration value="Time" />
			<xs:enumeration value="Volume" />
			<xs:enumeration value="VolumetricDensity" />
			<xs:enumeration value="VolumetricFlowRate" />
		</xs:restriction>
	</xs:simpleType>
	
</xs:schema>

=== openhab/openhab-core/tools/i18n-plugin/src/test/resources/acmeweather.bundle/OH-INF/thing/channel-types.xml
<?xml version="1.0" encoding="UTF-8"?>
<thing:thing-descriptions bindingId="acmeweather"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:thing="https://openhab.org/schemas/thing-description/v1.0.0"
	xsi:schemaLocation="https://openhab.org/schemas/thing-description/v1.0.0 https://openhab.org/schemas/thing-description-1.0.0.xsd">

	<!-- Channel Group -->
	<channel-group-type id="forecast">
		<label>Weather information group</label>
		<description>Weather information group description.</description>
		<channels>
			<channel id="temperature" typeId="temperature"/>
			<channel id="minTemperature" typeId="temperature">
				<label>Min. Temperature</label>
				<description>Minimum forecasted temperature in degrees Celsius (metric) or Fahrenheit (imperial).</description>
			</channel>
			<channel id="maxTemperature" typeId="temperature">
				<label>Max. Temperature</label>
				<description>Maximum forecasted temperature in degrees Celsius (metric) or Fahrenheit (imperial).</description>
			</channel>
		</channels>
	</channel-group-type>

	<!-- Channel -->
	<channel-type id="temperature">
		<item-type>Number</item-type>
		<label>Temperature</label>
		<description>Temperature in degrees Celsius (metric) or Fahrenheit (imperial).</description>
		<state pattern="%d degree Celsius">
			<options>
				<option value="VALUE">My label</option>
			</options>
		</state>
	</channel-type>

	<channel-type id="time-stamp">
		<item-type>DateTime</item-type>
		<label>Observation Time</label>
		<description>Time of data observation.</description>
		<category>Time</category>
		<state readOnly="true" pattern="%1$tY-%1$tm-%1$td %1$tH:%1$tM:%1$tS"/>
	</channel-type>

</thing:thing-descriptions>

=== openhab/openhab-core/bundles/org.openhab.core.test.magic/src/main/resources/ESH-INF/thing/bridge-types.xml
<?xml version="1.0" encoding="UTF-8"?>
<thing:thing-descriptions bindingId="magic"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:thing="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0"
	xsi:schemaLocation="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0 http://eclipse.org/smarthome/schemas/thing-description-1.0.0.xsd">

	<bridge-type id="magic-bridge1">
		<label>Magic Bridge 1</label>
		<description>The 1st magic bridge</description>
	</bridge-type>
	<bridge-type id="magic-bridge2">
		<label>Magic Bridge 2</label>
		<description>The 2nd magic bridge</description>
	</bridge-type>

	<thing-type id="bridgedThing">
		<supported-bridge-type-refs>
			<bridge-type-ref id="magic-bridge1" />
			<bridge-type-ref id="magic-bridge2" />
		</supported-bridge-type-refs>
		<label>Magic Bridged Thing</label>
		<description>A magic bridged thing.</description>
	</thing-type>

</thing:thing-descriptions>

=== openhab/openhab-core/bundles/tests/org.openhab.core.thing.xml.tests/src/test/resources/test-bundle-pool/SystemChannels.bundle/src/main/resources/ESH-INF/thing/thing-types.xml
<?xml version="1.0" encoding="UTF-8"?>
<thing:thing-descriptions bindingId="SystemChannels"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:thing="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0"
	xsi:schemaLocation="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0 http://eclipse.org/smarthome/schemas/thing-description-1.0.0.xsd">

	<!-- YahooWeather Binding -->
	<thing-type id="wireless-router">
		<label>Simple wireless router</label>
		<description>Simple wireless router</description>

		<channels>
			<channel id="sigstr" typeId="system.signal-strength">
				<label>My special Signal Strength</label>
				<description>My special description for Signal Strength</description>
			</channel>
			<channel id="test" typeId="system.my-channel" />
			<channel id="lowbat" typeId="system.low-battery" />
		</channels>

	</thing-type>

	<!-- System Channel Type -->
	<channel-type id="my-channel" system="true">
		<item-type>Number</item-type>
		<label>My Channel</label>
		<category>Other</category>
		<tags>
			<tag>
				Test
			</tag>
		</tags>
		<config-description>
			<parameter name="range" type="integer" readOnly="true" min="0" max="4" step="1" />
		</config-description>
	</channel-type>

</thing:thing-descriptions>

=== openhab/openhab-core/tools/archetype/binding/src/main/resources/archetype-resources/src/main/resources/OH-INF/thing/thing-types.xml
<?xml version="1.0" encoding="UTF-8"?>
<thing:thing-descriptions bindingId="${bindingId}"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:thing="https://openhab.org/schemas/thing-description/v1.0.0"
	xsi:schemaLocation="https://openhab.org/schemas/thing-description/v1.0.0 https://openhab.org/schemas/thing-description-1.0.0.xsd">

	<!-- Sample Thing Type -->
	<thing-type id="sample">
		<label>${bindingIdCamelCase} Binding Thing</label>
		<description>Sample thing for ${bindingIdCamelCase} Binding</description>

		<channels>
			<channel id="channel1" typeId="sample-channel"/>
		</channels>

		<config-description>
			<parameter name="config1" type="text" required="true">
				<label>Sample Parameter</label>
				<description>This is a sample text configuration parameter</description>
			</parameter>
		</config-description>

	</thing-type>

	<!-- Sample Channel Type -->
	<channel-type id="sample-channel">
		<item-type>${bindingId}Item</item-type>
		<label>${bindingIdCamelCase} Binding Channel</label>
		<description>Sample channel for ${bindingIdCamelCase} Binding</description>
	</channel-type>

</thing:thing-descriptions>

=== openhab/openhab-core/bundles/org.openhab.core.test.magic/src/main/resources/OH-INF/thing/channel-types.xml
<?xml version="1.0" encoding="UTF-8"?>
<thing:thing-descriptions bindingId="magic"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:thing="https://openhab.org/schemas/thing-description/v1.0.0"
	xsi:schemaLocation="https://openhab.org/schemas/thing-description/v1.0.0 https://openhab.org/schemas/thing-description-1.0.0.xsd">

	<channel-type id="switch">
		<item-type>Switch</item-type>
		<label>Switch</label>
		<description>The on/off channel allows to toggle between on and off.</description>
		<autoUpdatePolicy>recommend</autoUpdatePolicy>
		<config-description>
			<parameter name="invert" type="boolean">
				<label>Invert operation</label>
			</parameter>
		</config-description>
	</channel-type>

	<channel-type id="brightness">
		<item-type>Dimmer</item-type>
		<label>Dimmer</label>
		<description>The dimmer channel allows to control the brightness.</description>
		<category>DimmableLight</category>
		<autoUpdatePolicy>recommend</autoUpdatePolicy>
	</channel-type>

	<channel-type id="color">
		<item-type>Color</item-type>
		<label>Color</label>
		<description>The color channel allows to control the color of a light.
			It is also possible to dim values and switch the
			light on and off.
		</description>
		<category>ColorLight</category>
		<tags>
			<tag>Lighting</tag>
		</tags>
		<autoUpdatePolicy>recommend</autoUpdatePolicy>
		<config-description>
			<parameter name="boostRed" type="decimal" min="0" max="100">
				<label>Red boost</label>
				<description>Boost the red color channel (in percent)</description>
			</parameter>
			<parameter name="boostGreen" type="decimal" min="0" max="100">
				<label>Green boost</label>
				<description>Boost the green color channel (in percent)</description>
			</parameter>
			<parameter name="boostBlue" type="decimal" min="0" max="100">
				<label>Blue boost</label>
				<description>Boost the blue color channel (in percent)</description>
			</parameter>
		</config-description>
	</channel-type>

	<channel-type id="alert" advanced="true">
		<item-type>String</item-type>
		<label>Alert</label>
		<description>The alert channel allows a temporary change to the bulbâ€™s state.</description>
		<command>
			<options>
				<option value="NONE">None</option>
				<option value="SELECT">Alert</option>
				<option value="LSELECT">Long Alert</option>
			</options>
		</command>

		<autoUpdatePolicy>recommend</autoUpdatePolicy>
	</channel-type>

	<channel-type id="contact">
		<item-type>Contact</item-type>
		<label>Contact</label>
		<state readOnly="true"></state>
		<autoUpdatePolicy>recommend</autoUpdatePolicy>
	</channel-type>

	<channel-type id="location">
		<item-type>Location</item-type>
		<label>Location</label>
		<autoUpdatePolicy>recommend</autoUpdatePolicy>
	</channel-type>

	<channel-type id="number">
		<item-type>Number</item-type>
		<label>Thing Online(&gt;0)/Offline(&lt;0) Delay</label>
		<autoUpdatePolicy>recommend</autoUpdatePolicy>
	</channel-type>

	<channel-type id="text">
		<item-type>String</item-type>
		<label>Text channel</label>
		<autoUpdatePolicy>recommend</autoUpdatePolicy>
	</channel-type>

	<channel-type id="systemcommand">
		<item-type>String</item-type>
		<label>Send system command</label>
		<description>Sends a system command to Kodi. This allows to shutdown/suspend/hibernate/reboot/quit Kodi.</description>
	</channel-type>

	<channel-type id="temperature">
		<item-type>Number:Temperature</item-type>
		<label>Current Temperature</label>
		<state readOnly="true" pattern="%.1f %unit%"/>
	</channel-type>

	<channel-type id="set-temperature">
		<item-type>Number:Temperature</item-type>
		<label>Set Point</label>
		<state readOnly="false" pattern="%.1f %unit%" min="12" max="38" step="0.5"/>
		<autoUpdatePolicy>recommend</autoUpdatePolicy>
	</channel-type>

	<channel-type id="choosy">
		<item-type>Number</item-type>
		<label>Choosy</label>
		<state>
			<options>
				<option value="0">Zero</option>
				<option value="1">One</option>
				<option value="2">Two</option>
			</options>
		</state>
		<autoUpdatePolicy>recommend</autoUpdatePolicy>
	</channel-type>

	<channel-type id="rollershutter">
		<item-type>Rollershutter</item-type>
		<label>Rollershutter</label>
		<autoUpdatePolicy>recommend</autoUpdatePolicy>
	</channel-type>

	<channel-type id="player">
		<item-type>Player</item-type>
		<label>Player</label>
		<autoUpdatePolicy>recommend</autoUpdatePolicy>
	</channel-type>

	<channel-type id="image">
		<item-type>Image</item-type>
		<label>Image</label>
	</channel-type>

	<channel-type id="trigger">
		<kind>trigger</kind>
		<label>Trigger</label>
		<event>
			<options>
				<option value="ON">Switched on</option>
				<option value="OFF">Switched off</option>
			</options>
		</event>
	</channel-type>

</thing:thing-descriptions>

=== openhab/openhab-core/itests/org.openhab.core.thing.xml.tests/src/main/resources/test-bundle-pool/SystemChannelsNoThingTypes.bundle/src/main/resources/ESH-INF/thing/thing-types.xml
<?xml version="1.0" encoding="UTF-8"?>
<thing:thing-descriptions bindingId="SystemChannelsNoThingTypes"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:thing="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0"
        xsi:schemaLocation="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0 http://eclipse.org/smarthome/schemas/thing-description-1.0.0.xsd">
        
    <!-- System Channel Type -->
	<channel-type id="my-syschannel" system="true">
		<item-type>Number</item-type>
		<label>My System Channel</label>
		<category>Other</category>
		<tags>
			<tag>
				Test
			</tag>
		</tags>
		<config-description>
			<parameter name="range" type="integer" readOnly="true" min="0"
				max="4" step="1" />
		</config-description>
	</channel-type>
</thing:thing-descriptions>

=== openhab/openhab-core/tools/i18n-plugin/src/test/resources/acmeweather.bundle/OH-INF/thing/thing-types.xml
<?xml version="1.0" encoding="UTF-8"?>
<thing:thing-descriptions bindingId="acmeweather"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:thing="https://openhab.org/schemas/thing-description/v1.0.0"
	xsi:schemaLocation="https://openhab.org/schemas/thing-description/v1.0.0 https://openhab.org/schemas/thing-description-1.0.0.xsd">

	<!-- ACME Weather Binding -->
	<thing-type id="weather">
		<label>Weather Information *</label>
		<description>@text/CUSTOM_KEY</description>

		<channels>
			<channel id="temperature" typeId="temperature"/>
			<channel id="minTemperature" typeId="temperature">
				<label>Min. Temperature</label>
				<description>Minimum temperature in degrees Celsius (metric) or Fahrenheit (imperial).</description>
			</channel>
			<channel id="time-stamp" typeId="time-stamp"/>
		</channels>

		<config-description-ref uri="thing-type:acmeweather:weather"/>
	</thing-type>

	<!-- ACME Weather Binding with group -->
	<thing-type id="weather-with-group">
		<label>Weather Information with Group</label>

		<channel-groups>
			<channel-group id="forecastToday" typeId="forecast">
				<label>Today</label>
				<description>This is the weather forecast for today.</description>
			</channel-group>
			<channel-group id="forecastTomorrow" typeId="forecast">
				<label>Weather Forecast Tomorrow</label>
				<description>This is the weather forecast for tomorrow.</description>
			</channel-group>
		</channel-groups>
	</thing-type>

</thing:thing-descriptions>

=== openhab/openhab-core/itests/org.openhab.core.thing.xml.tests/example/example.xml
<?xml version="1.0" encoding="UTF-8"?>
<thing:thing-descriptions bindingId="hue"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:thing="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0"
    xsi:schemaLocation="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0 http://eclipse.org/smarthome/schemas/thing-description-1.0.0.xsd">

    <!-- Hue Lamp -->
    <thing-type id="lamp">
        <supported-bridge-type-refs>
            <bridge-type-ref id="bridge" />
        </supported-bridge-type-refs>

        <label>HUE Lamp</label>
        <description>My own great HUE Lamp.</description>

        <channel-groups>
            <channel-group id="alarm_system" typeId="alarm_system"/>
        </channel-groups>
    </thing-type>

    <!-- Color Channel -->
    <channel-type id="color">
        <item-type>Color</item-type>
        <label>Color</label>
        <description>The color channel allows to control the color of a light.
            It is also possible to dim values and switch the light on and off.
        </description>
        <tags>
            <tag>Hue</tag>
            <tag>ColorLamp</tag>
        </tags>

        <config-description>
            <parameter name="lastDimValue" type="boolean" />
        </config-description>
    </channel-type>

    <!-- Brightness Channel -->
    <channel-type id="brightness">
        <item-type>Dimmer</item-type>
        <label>Brightness</label>
        <description>The brightness channel allows to control the brightness of a light.
            It is also possible to switch the light on and off.
        </description>
        <tags>
            <tag>Hue</tag>
            <tag>DimmableLamp</tag>
        </tags>

        <config-description>
            <parameter name="lastDimValue" type="boolean" />
        </config-description>
    </channel-type>

    <!-- Color Temperature Channel -->
    <channel-type id="color_temperature">
        <item-type>Dimmer</item-type>
        <label>Color Temperature</label>
        <description>The color temperature channel allows to set the color
            temperature of a light from 0 (cold) to 100 (warm).</description>
        <tags>
            <tag>Hue</tag>
            <tag>AmbientLamp</tag>
        </tags>
    </channel-type>

    <!-- Alarm Channel -->
    <channel-type id="alarm">
        <item-type>Number</item-type>
        <label>Alarm System</label>
        <description>The light blinks if alarm is set.</description>
        <category>ALARM</category>
        <tags>
            <tag>Hue</tag>
            <tag>AlarmSystem</tag>
        </tags>
        <state min="0" max="100.0" step="10.0" pattern="%d Peek">
            <options>
                <option value="SOUND">My great sound.</option>
                <option value="LIGHT"/>
            </options>
        </state>
    </channel-type>

    <!-- Motion Channel -->
    <channel-type id="motion" advanced="true">
        <item-type>Number</item-type>
        <label>Motion Sensor</label>
        <description>The sensor detecting motion.</description>
        <category>MOTION</category>
        <tags>
            <tag>Hue</tag>
            <tag>AlarmSystem</tag>
        </tags>
    </channel-type>

    <!-- Alarm System Channel -->
    <channel-group-type id="alarm_system" advanced="false">
        <label>Alarm System</label>
        <description>The alarm system.</description>
        <channels>
            <channel id="colorId" typeId="color" />
            <channel id="color_temperatureId" typeId="color_temperature" />
            <channel id="alarmId" typeId="alarm" />
            <channel id="motionId" typeId="motion"/>
        </channels>
    </channel-group-type>

</thing:thing-descriptions>
