=== openhab/openhab-core/bundles/org.openhab.core.thing.xml/thing-description-1.0.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
        xmlns:thing-description="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0"
        xmlns:config-description="http://eclipse.org/smarthome/schemas/config-description/v1.0.0"
        targetNamespace="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0">

    <xs:import namespace="http://eclipse.org/smarthome/schemas/config-description/v1.0.0"
            schemaLocation="http://eclipse.org/smarthome/schemas/config-description-1.0.0.xsd"/>

    <xs:element name="thing-descriptions">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element name="thing-type" type="thing-description:thingType"/>
                <xs:element name="bridge-type" type="thing-description:bridgeType"/>
                <xs:element name="channel-type" type="thing-description:channelType"/>
                <xs:element name="channel-group-type" type="thing-description:channelGroupType"/>
            </xs:choice>
            <xs:attribute name="bindingId" type="config-description:idRestrictionPattern" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="thingType">
        <xs:sequence>
            <xs:element name="supported-bridge-type-refs" type="thing-description:supportedBridgeTypeRefs" minOccurs="0"/>
            <xs:element name="label" type="xs:string"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
            <xs:element name="category" type="xs:string" minOccurs="0"/>
            <xs:choice minOccurs="0">
                <xs:element name="channels" type="thing-description:channels"/>
                <xs:element name="channel-groups" type="thing-description:channelGroups"/>
            </xs:choice>
            <xs:element name="properties" type="thing-description:properties" minOccurs="0"/>
            <xs:element name="representation-property" type="xs:string" minOccurs="0"/>
            <xs:choice minOccurs="0">
                <xs:element name="config-description" type="config-description:configDescription"/>
                <xs:element name="config-description-ref" type="config-description:configDescriptionRef"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="id" type="config-description:idRestrictionPattern" use="required"/>
        <xs:attribute name="listed" type="xs:boolean" default="true" use="optional"/>
        <xs:attribute name="extensible" type="thing-description:namespaceIdListRestrictionPattern" use="optional"/>
    </xs:complexType>
    
    <xs:simpleType name="namespaceIdListRestrictionPattern">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z0-9\-_.]+(,( )?[A-Za-z0-9\-_.]+)*" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="bridgeType">
        <xs:complexContent>
            <xs:extension base="thing-description:thingType"/>
        </xs:complexContent>
    </xs:complexType>

    <xs:simpleType name="auto-update-policy">
        <xs:restriction base="xs:string">
            <xs:enumeration value="veto" />
            <xs:enumeration value="default" />
            <xs:enumeration value="recommend" />
        </xs:restriction>
    </xs:simpleType>    

    <xs:complexType name="channelType">
        <xs:sequence>
            <xs:element name="item-type" type="xs:string" minOccurs="0"/>
            <xs:element name="kind" type="xs:string" minOccurs="0"/>
            <xs:element name="label" type="xs:string"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
            <xs:element name="category" type="xs:string" minOccurs="0"/>
            <xs:element name="tags" type="thing-description:tags" minOccurs="0"/>
            <xs:element name="state" type="thing-description:state" minOccurs="0"/>
            <xs:element name="command" type="thing-description:command" minOccurs="0"/>
            <xs:element name="event" type="thing-description:event" minOccurs="0"/>
            <xs:element name="autoUpdatePolicy" type="thing-description:auto-update-policy" minOccurs="0"/>
            <xs:choice minOccurs="0">
                <xs:element name="config-description" type="config-description:configDescription"/>
                <xs:element name="config-description-ref" type="config-description:configDescriptionRef"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="id" type="config-description:idRestrictionPattern" use="required"/>
        <xs:attribute name="advanced" type="xs:boolean" default="false" use="optional"/>
        <xs:attribute name="system" type="xs:boolean" default="false" use="optional"/>
    </xs:complexType>

    <xs:complexType name="channelGroupType">
        <xs:sequence>
            <xs:element name="label" type="xs:string"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
            <xs:element name="category" type="xs:string" minOccurs="0"/>
            <xs:element name="channels" type="thing-description:channels" minOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="id" type="config-description:idRestrictionPattern" use="required"/>
        <xs:attribute name="advanced" type="xs:boolean" default="false" use="optional"/>
    </xs:complexType>

    <xs:complexType name="supportedBridgeTypeRefs">
        <xs:sequence>
            <xs:element name="bridge-type-ref" type="thing-description:bridgeTypeRef" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="bridgeTypeRef">
        <xs:attribute name="id" type="config-description:idRestrictionPattern" use="required"/>
    </xs:complexType>

    <xs:complexType name="channels">
        <xs:sequence>
            <xs:element name="channel" type="thing-description:channel" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="namespaceIdRestrictionPattern">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z0-9\-_.]+" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="channel">
        <xs:sequence>
            <xs:element name="label" type="xs:string" minOccurs="0"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
            <xs:element name="properties" type="thing-description:properties" minOccurs="0"/>
            <xs:element name="autoUpdatePolicy" type="thing-description:auto-update-policy" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="id" type="config-description:idRestrictionPattern" use="required"/>
        <xs:attribute name="typeId" type="thing-description:namespaceIdRestrictionPattern" use="required"/>
    </xs:complexType>

    <xs:complexType name="channelGroups">
        <xs:sequence>
            <xs:element name="channel-group" type="thing-description:channelGroup" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="channelGroup">
        <xs:sequence>
            <xs:element name="label" type="xs:string" minOccurs="0"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="id" type="config-description:idRestrictionPattern" use="required"/>
        <xs:attribute name="typeId" type="config-description:idRestrictionPattern" use="required"/>
    </xs:complexType>

    <xs:complexType name="tags">
        <xs:sequence>
            <xs:element name="tag" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="state">
        <xs:sequence>
            <xs:element name="options" type="thing-description:options" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="min" type="xs:decimal" use="optional"/>
        <xs:attribute name="max" type="xs:decimal" use="optional"/>
        <xs:attribute name="step" type="xs:decimal" use="optional"/>
        <xs:attribute name="pattern" type="xs:string" use="optional"/>
        <xs:attribute name="readOnly" type="xs:boolean" default="false" use="optional"/>
    </xs:complexType>

    <xs:complexType name="event">
        <xs:sequence>
            <xs:element name="options" type="thing-description:options" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="options">
        <xs:sequence>
            <xs:element name="option" type="thing-description:option" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="command">
        <xs:sequence>
            <xs:element name="options" type="thing-description:options" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="option">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="value" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

	<xs:complexType name="properties">
		<xs:sequence>
			<xs:element name="property" type="thing-description:property" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="property">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="name" type="xs:string" use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:simpleType name="dimension">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Intensity" />
			<xs:enumeration value="Acceleration" />
			<xs:enumeration value="AmountOfSubstance" />
			<xs:enumeration value="Angle" />
			<xs:enumeration value="AngularAcceleration" />
			<xs:enumeration value="AngularVelocity" />
			<xs:enumeration value="Area" />
			<xs:enumeration value="CatalyticActivity" />
			<xs:enumeration value="DataAmount" />
			<xs:enumeration value="DataRate" />
			<xs:enumeration value="Dimensionless" />
			<xs:enumeration value="Duration" />
			<xs:enumeration value="DynamicViscosity" />
			<xs:enumeration value="ElectricCapacitance" />
			<xs:enumeration value="ElectricCharge" />
			<xs:enumeration value="ElectricConductance" />
			<xs:enumeration value="ElectricCurrent" />
			<xs:enumeration value="ElectricInductance" />
			<xs:enumeration value="ElectricPotential" />
			<xs:enumeration value="ElectricResistance" />
			<xs:enumeration value="Energy" />
			<xs:enumeration value="Force" />
			<xs:enumeration value="Frequency" />
			<xs:enumeration value="Illuminance" />
			<xs:enumeration value="KinematicViscosity" />
			<xs:enumeration value="Length" />
			<xs:enumeration value="LuminousFlux" />
			<xs:enumeration value="LuminousIntensity" />
			<xs:enumeration value="MagneticFlux" />
			<xs:enumeration value="MagneticFluxDensity" />
			<xs:enumeration value="Mass" />
			<xs:enumeration value="MassFlowRate" />
			<xs:enumeration value="Power" />
			<xs:enumeration value="Pressure" />
			<xs:enumeration value="RadiationDoseAbsorbed" />
			<xs:enumeration value="RadiationDoseEffective" />
			<xs:enumeration value="RadioactiveActivity" />
			<xs:enumeration value="SolidAngle" />
			<xs:enumeration value="Speed" />
			<xs:enumeration value="Temperature" />
			<xs:enumeration value="Torque" />
			<xs:enumeration value="Velocity" />
			<xs:enumeration value="Time" />
			<xs:enumeration value="Volume" />
			<xs:enumeration value="VolumetricDensity" />
			<xs:enumeration value="VolumetricFlowRate" />
		</xs:restriction>
	</xs:simpleType>
	
</xs:schema>

=== openhab/openhab-core/itests/org.openhab.core.config.xml.tests/src/main/resources/test-bundle-pool/ConfigDescriptionsFragmentTest.host/src/main/resources/ESH-INF/thing/MyThingType.xml
<?xml version="1.0" encoding="UTF-8"?>
<thing:thing-descriptions bindingId="hue"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:thing="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0"
    xsi:schemaLocation="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0 http://eclipse.org/smarthome/schemas/thing-description-1.0.0.xsd">

    <thing-type id="MyThingType">
        <label>My Thing Type</label>
        <description>My Thing Type</description>

        <config-description>
            <parameter name="myID" type="text">
                <label>My ID</label>
                <description>My ID.</description>
            </parameter>
        </config-description>
    </thing-type>
</thing:thing-descriptions>

=== openhab/openhab-core/itests/org.openhab.core.thing.tests/src/main/resources/test-bundle-pool/ChannelTypesI18nTest.bundle/OH-INF/thing/thing-types.xml
<?xml version="1.0" encoding="UTF-8"?>
<thing:thing-descriptions bindingId="somebinding"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:thing="https://openhab.org/schemas/thing-description/v1.0.0"
	xsi:schemaLocation="https://openhab.org/schemas/thing-description/v1.0.0 https://openhab.org/schemas/thing-description-1.0.0.xsd">

	<thing-type id="something">

		<label>Something</label>

		<channels>
			<channel id="channelPlain" typeId="string">
				<label>Channel Plain Label</label>
				<description>Channel Plain Description</description>
			</channel>
			<channel id="channelInplace" typeId="channel-with-i18n">
				<label>@text/channelInplaceLabel</label>
				<description>@text/channelInplaceDescription</description>
			</channel>
		</channels>
	</thing-type>

	<channel-type id="channel-with-i18n">
		<item-type>Number</item-type>
		<label>@text/channelLabel</label>
		<description>@text/channelDescription</description>
		<command>
			<options>
				<option value="ALARM">Alarm</option>
				<option value="LONG_ALARM"/>
			</options>
		</command>
	</channel-type>

	<channel-group-type id="channelgroup-with-i18n">

		<label>@text/channelGroupLabel</label>
		<description>@text/channelGroupDescription</description>

		<channels>
			<channel id="channelPlain" typeId="string">
				<label>Channel Plain Label</label>
				<description>Channel Plain Description</description>
			</channel>
			<channel id="channelInplace" typeId="channel-with-i18n">
				<label>@text/channelInplaceLabel</label>
				<description>@text/channelInplaceDescription</description>
			</channel>
		</channels>
	</channel-group-type>

</thing:thing-descriptions>

=== openhab/openhab-core/itests/org.openhab.core.thing.xml.tests/src/test/resources/test-bundle-pool/SystemChannelsInChannelGroups.bundle/src/main/resources/ESH-INF/thing/thing-types.xml
<?xml version="1.0" encoding="UTF-8"?>
<thing:thing-descriptions bindingId="SystemChannelsInChannelGroups" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:thing="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0"
	xsi:schemaLocation="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0 http://eclipse.org/smarthome/schemas/thing-description-1.0.0.xsd">

	<!-- YahooWeather Binding -->
	<thing-type id="wireless-router">
		<label>Simple wireless router</label>
		<description>Simple wireless router</description>

		<channel-groups>
			<channel-group typeId="channelGroup" id="group1" />
			<channel-group typeId="channelGroup" id="group2" />
		</channel-groups>

	</thing-type>

	<!-- System Channel Type -->
	<channel-type id="my-channel" system="true">
		<item-type>Number</item-type>
		<label>My Channel</label>
		<category>Other</category>
		<tags>
			<tag>
				Test
			</tag>
		</tags>
		<config-description>
			<parameter name="range" type="integer" readOnly="true" min="0" max="4" step="1" />
		</config-description>
	</channel-type>

	<!-- Channel Group -->
	<channel-group-type id="channelGroup">
		<label>Test Channel Group Label</label>
		<description>Test Channel Group Description</description>
		<channels>
			<channel id="sigstr" typeId="system.signal-strength" />
			<channel id="test" typeId="system.my-channel" />
			<channel id="lowbat" typeId="system.low-battery" />
		</channels>
	</channel-group-type>

</thing:thing-descriptions>

=== openhab/openhab-core/itests/org.openhab.core.thing.xml.tests/src/main/resources/test-bundle-pool/SystemChannelsUser.bundle/src/main/resources/ESH-INF/thing/thing-types.xml
<?xml version="1.0" encoding="UTF-8"?>
<thing:thing-descriptions bindingId="SystemChannelsUser"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:thing="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0"
        xsi:schemaLocation="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0 http://eclipse.org/smarthome/schemas/thing-description-1.0.0.xsd">

    <thing-type id="wireless-router-v2">
        <label>Simple wireless router</label>
        <description>Simple wireless router</description>

		<channels>
			<channel id="sigstrv2" typeId="system.signal-strength" />
			<channel id="test" typeId="system.my-channel" />
			<channel id="lowbat" typeId="system.low-battery" />
		</channels>

    </thing-type> 
</thing:thing-descriptions>

=== openhab/openhab-core/bundles/org.openhab.core.test.magic/src/main/resources/OH-INF/thing/thing-types.xml
<?xml version="1.0" encoding="UTF-8"?>
<thing:thing-descriptions bindingId="magic"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:thing="https://openhab.org/schemas/thing-description/v1.0.0"
	xsi:schemaLocation="https://openhab.org/schemas/thing-description/v1.0.0 https://openhab.org/schemas/thing-description-1.0.0.xsd">

	<thing-type id="extensible-thing" extensible="brightness,color,alert,choosy,image">
		<label>Magic Light - Extensible</label>
		<description>A generic light thing with extension channels</description>
		<config-description>
		</config-description>
	</thing-type>

	<thing-type id="onoff-light" extensible="alert">
		<label>Magic Light - On/Off</label>
		<description>A on/off light</description>

		<channels>
			<channel id="switch" typeId="switch"/>
			<channel id="trigger" typeId="trigger"/>
		</channels>

		<config-description>
		</config-description>
	</thing-type>

	<thing-type id="dimmable-light" extensible="alert,color">
		<label>Magic Light - Dimmable</label>
		<description>A dimmable light</description>

		<channels>
			<channel id="brightness" typeId="brightness"/>
		</channels>

		<config-description>
		</config-description>
	</thing-type>

	<thing-type id="color-light">
		<label>Magic Light - Color</label>
		<description>A dimmable light with changeable colors.</description>

		<channels>
			<channel id="color" typeId="color"/>
			<channel id="alert" typeId="alert"/>
		</channels>

		<config-description>
		</config-description>
	</thing-type>

	<thing-type id="contact-sensor">
		<label>Magic Sensor - Door/Window Contact</label>
		<description>A door/window sensor indicating an open/close status.</description>

		<channels>
			<channel id="contact" typeId="contact"/>
		</channels>
	</thing-type>

	<thing-type id="location-thing">
		<label>Magic Location</label>
		<description>A location thing providing a location channel.</description>

		<channels>
			<channel id="location" typeId="location"/>
		</channels>
	</thing-type>

	<thing-type id="configurable-thing">
		<label>Magic Configurable Thing</label>
		<description>A thing that can be configured.</description>
		<channels>
			<channel id="switch" typeId="switch"/>
		</channels>

		<representation-property>serialNumber</representation-property>

		<config-description uri="thing-type:magic:config">
			<parameter name="interval" type="integer" min="1" max="100">
				<label>Integer</label>
				<description>Integer value between 1 and 100.</description>
				<default>23</default>
			</parameter>
		</config-description>
	</thing-type>

	<thing-type id="thermostat">
		<label>Magic Thermostat</label>
		<description>A thermostat for set point and current temperature.</description>

		<channels>
			<channel typeId="temperature" id="temperature"></channel>
			<channel typeId="set-temperature" id="set-temperature"></channel>
		</channels>
	</thing-type>

	<thing-type id="delayed-thing">
		<label>Magic Delayed Online Thing</label>
		<description>A thing that goes online after some time.</description>

		<channels>
			<channel id="number" typeId="number"/>
		</channels>
	</thing-type>

	<thing-type id="chatty-thing">
		<label>Magic ChattyThing</label>
		<description>A thing that periodically sends data.</description>

		<channels>
			<channel id="number" typeId="number">
				<label>Number to show</label>
			</channel>
			<channel id="text" typeId="text">
				<label>Text to show</label>
			</channel>
		</channels>

		<config-description uri="thing-type:magic:chattyConfig">
			<parameter name="interval" type="integer">
				<label>Interval</label>
				<description>Interval to send data in seconds. (Use 0 to disable data sending)</description>
				<default>5</default>
			</parameter>
		</config-description>
	</thing-type>

	<thing-type id="firmware-update">
		<label>Magic Firmware Updatable Thing</label>
		<description>A thing which allows updating its firmware</description>

		<properties>
			<property name="firmwareVersion">0.1.0</property>
		</properties>

		<config-description uri="thing-type:magic:update-config">
			<parameter name="updateModel" type="text" required="true">
				<required>true</required>
				<options>
					<option value="Alohomora">Alohomora</option>
					<option value="Colloportus">Colloportus</option>
					<option value="Lumos">Lumos</option>
					<option value="Nox">Nox</option>
				</options>
				<label>Model ID</label>
				<description>The model of the magic firmware update thing</description>
				<default>Not specified</default>
			</parameter>
		</config-description>

	</thing-type>

	<thing-type id="rollershutter">
		<label>Magic Rollershutter Thing</label>
		<description>A rollershutter</description>
		<channels>
			<channel typeId="rollershutter" id="rollershutter"></channel>
		</channels>
	</thing-type>

	<thing-type id="player">
		<label>Magic Player Thing</label>
		<description>A media player</description>
		<channels>
			<channel typeId="player" id="player"></channel>
		</channels>
	</thing-type>

	<thing-type id="image">
		<label>Magic Image</label>
		<description>A thing providing an image</description>
		<channels>
			<channel typeId="image" id="image"></channel>
		</channels>
		<config-description>
			<parameter name="source" type="text" required="true">
				<label>Image URL</label>
				<description>The URL the image will be loaded from</description>
				<context>url</context>
			</parameter>
		</config-description>
	</thing-type>

	<thing-type id="action-module">
		<label>Magic ActionModule Thing</label>
		<description>A Thing with an ActionModule</description>
		<channels>
			<channel typeId="switch" id="switch"></channel>
		</channels>
		<config-description>
			<parameter name="textParam" type="text" required="true">
				<label>Text Parameter</label>
				<description>Just a text</description>
			</parameter>
		</config-description>
	</thing-type>

	<thing-type id="dynamic-state-description">
		<label>Magic DynamicStateDescription Thing</label>
		<description>A Thing with a DynamicStateDescription</description>
		<channels>
			<channel typeId="systemcommand" id="systemcommand"/>
			<channel typeId="system.signal-strength" id="signal-strength"/>
		</channels>
		<config-description>
			<parameter name="textParam" type="text" required="true">
				<label>Text Parameter</label>
				<description>Just a text</description>
			</parameter>
		</config-description>
	</thing-type>

	<thing-type id="online-offline">
		<label>Magic Online Offline</label>
		<description>An online/offline toggle thing</description>
		<config-description>
			<parameter name="toggleTime" type="integer" required="true">
				<label>Toggle Time</label>
				<description>The time in seconds to toggle between ONLINE and OFFLINE status.</description>
			</parameter>
		</config-description>
	</thing-type>
</thing:thing-descriptions>

=== openhab/openhab-core/itests/org.openhab.core.thing.xml.tests/src/main/resources/test-bundle-pool/yahooweather.bundle/ESH-INF/thing/thing-types.xml
<?xml version="1.0" encoding="UTF-8"?>
<thing:thing-descriptions bindingId="yahooweather"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:thing="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0"
	xsi:schemaLocation="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0 http://eclipse.org/smarthome/schemas/thing-description-1.0.0.xsd">

	<!-- YahooWeather Binding -->
	<thing-type id="weather">
		<label>Weather Information *</label>
		<description>@text/CUSTOM_KEY</description>

		<channels>
			<channel id="temperature" typeId="temperature" />
			<channel id="minTemperature" typeId="temperature">
				<label>Min. Temperature</label>
				<description>Minimum temperature in degrees celsius (metric) or fahrenheit (imperial).</description>
			</channel>
		</channels>
	</thing-type>

	<!-- YahooWeather Binding with group -->
	<thing-type id="weather-with-group">
		<label>Weather Information with Group</label>

		<channel-groups>
			<channel-group id="forecastToday" typeId="forecast">
				<label>Today</label>
				<description>This is the weather forecast for today.</description>
			</channel-group>
			<channel-group id="forecastTomorrow" typeId="forecast">
				<label>Weather Forecast Tomorrow</label>
				<description>This is the weather forecast for tomorrow.</description>
			</channel-group>
		</channel-groups>
	</thing-type>

	<!-- Channel Group -->
	<channel-group-type id="forecast">
		<label>Weather information group</label>
		<description>Weather information group description.</description>
		<channels>
			<channel id="temperature" typeId="temperature" />
			<channel id="minTemperature" typeId="temperature">
				<label>Min. Temperature</label>
				<description>Minimum forecasted temperature in degrees celsius (metric) or fahrenheit (imperial).</description>
			</channel>
			<channel id="maxTemperature" typeId="temperature">
				<label>Max. Temperature</label>
				<description>Maximum forecasted temperature in degrees celsius (metric) or fahrenheit (imperial).</description>
			</channel>
		</channels>
	</channel-group-type>

	<!-- Channel -->
	<channel-type id="temperature">
		<item-type>Number</item-type>
		<label>Temperature</label>
		<description>Temperature in degrees celsius (metric) or fahrenheit (imperial).</description>
		<state pattern="%d degree Celsius">
			<options>
				<option value="VALUE">My label</option>
			</options>
		</state>
	</channel-type>

</thing:thing-descriptions>
