=== openhab/openhab-core/bundles/org.openhab.core.thing/schema/update/update-description-1.0.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" jaxb:version="2.0"
           xmlns:update-description="https://openhab.org/schemas/update-description/v1.0.0"
           xmlns:thing-description="https://openhab.org/schemas/thing-description/v1.0.0"
           xmlns:config-description="https://openhab.org/schemas/config-description/v1.0.0"
           targetNamespace="https://openhab.org/schemas/update-description/v1.0.0">

    <xs:import namespace="https://openhab.org/schemas/config-description/v1.0.0"
               schemaLocation="https://openhab.org/schemas/config-description-1.0.0.xsd"/>
    <xs:import namespace="https://openhab.org/schemas/thing-description/v1.0.0"
               schemaLocation="https://openhab.org/schemas/thing-description-1.0.0.xsd"/>

    <xs:element name="update-descriptions">
        <xs:annotation>
            <xs:documentation>The root element of an update description. It contains the update instructions for managed
                things after thing-type changes. Instructions are grouped by thing-type and (internal) version.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="thing-type" type="update-description:thingType" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="thingType">
        <xs:sequence>
            <xs:element name="instruction-set" type="update-description:instructionSet" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="uid" type="update-description:thingTypeUid" use="required"/>
    </xs:complexType>

    <xs:complexType name="instructionSet">
        <xs:choice maxOccurs="unbounded">
            <xs:annotation>
                <xs:appinfo>
                    <jaxb:property name="instructions"/>
                </xs:appinfo>
            </xs:annotation>
            <xs:element name="add-channel" type="update-description:addChannel" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="update-channel" type="update-description:updateChannel" minOccurs="0"
                        maxOccurs="unbounded"/>
            <xs:element name="remove-channel" type="update-description:removeChannel" minOccurs="0"
                        maxOccurs="unbounded"/>
        </xs:choice>
        <xs:attribute name="targetVersion" type="xs:int" use="required"/>
    </xs:complexType>

    <xs:complexType name="addChannel">
        <xs:sequence>
            <xs:element name="type" type="update-description:channelTypeUid"/>
            <xs:element name="label" type="xs:string" minOccurs="0"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
            <xs:element name="tags" type="thing-description:tags" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="id" type="update-description:channelId" use="required"/>
        <xs:attribute name="groupIds" type="update-description:groupIds" />
    </xs:complexType>

    <xs:complexType name="updateChannel">
        <xs:annotation>
            <xs:documentation>Update a channel (e.g. change channel-type, label, description). By default, the old
                configuration and tags are copied to the new channel.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="type" type="update-description:channelTypeUid"/>
            <xs:element name="label" type="xs:string" minOccurs="0"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
            <xs:element name="tags" type="thing-description:tags" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>If set, already existing tags are overwritten.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="update-description:channelId" use="required"/>
        <xs:attribute name="groupIds" type="update-description:groupIds" />
        <xs:attribute name="preserveConfiguration" type="xs:boolean" default="true"/>
    </xs:complexType>

    <xs:complexType name="removeChannel">
        <xs:annotation>
            <xs:documentation>Remove a channel from a thing.</xs:documentation>
        </xs:annotation>
        <xs:attribute name="id" type="update-description:channelId" use="required"/>
        <xs:attribute name="groupIds" type="update-description:groupIds" />
    </xs:complexType>

    <xs:simpleType name="channelId">
        <xs:annotation>
            <xs:documentation>The simple id of the channel (i.e. without the thing UID).</xs:documentation>
        </xs:annotation>
        <xs:restriction base="config-description:idRestrictionPattern"/>
    </xs:simpleType>

    <xs:simpleType name="groupIds">
        <xs:annotation>
            <xs:documentation>A comma-separated list of channel-group-ids.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="thing-description:namespaceIdListRestrictionPattern"/>
    </xs:simpleType>

    <xs:simpleType name="channelTypeUid">
        <xs:annotation>
            <xs:documentation>The fully qualified UID of the channel type (e.g. "system:color",
                "viessmann:lastErrorMessage").
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="config-description:uriRestrictionPattern"/>
    </xs:simpleType>

    <xs:simpleType name="thingTypeUid">
        <xs:annotation>
            <xs:documentation>The fully qualified UID of the thing type.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="config-description:uriRestrictionPattern"/>
    </xs:simpleType>

</xs:schema>

=== openhab/openhab-core/itests/org.openhab.core.thing.tests/src/main/resources/test-bundle-pool/thingUpdateTest.bundle/OH-INF/update/multiInstructions.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<update:update-descriptions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:update="https://openhab.org/schemas/update-description/v1.0.0"
	xsi:schemaLocation="https://openhab.org/schemas/update-description/v1.0.0 https://openhab.org/schemas/update-description-1.0.0.xsd">

	<thing-type uid="testBinding:testThingTypeMultiple">
		<instruction-set targetVersion="1">
			<update-channel id="testChannel1">
				<type>testBinding:testChannelNewTypeId</type>
				<label>Test Label</label>
			</update-channel>
		</instruction-set>
		<instruction-set targetVersion="2">
			<add-channel id="testChannel2">
				<type>testBinding:testChannelOldTypeId</type>
				<label>TestLabel</label>
			</add-channel>
		</instruction-set>
		<instruction-set targetVersion="3">
			<remove-channel id="testChannel0"/>
		</instruction-set>
	</thing-type>

</update:update-descriptions>

=== openhab/openhab-core/itests/org.openhab.core.thing.tests/src/main/resources/test-bundle-pool/thingUpdateTest.bundle/OH-INF/update/singleInstructions.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<update:update-descriptions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:update="https://openhab.org/schemas/update-description/v1.0.0"
	xsi:schemaLocation="https://openhab.org/schemas/update-description/v1.0.0 https://openhab.org/schemas/update-description-1.0.0.xsd">

	<thing-type uid="testBinding:testThingTypeAdd">
		<instruction-set targetVersion="1">
			<add-channel id="testChannel1">
				<type>testBinding:testChannelTypeId</type>
			</add-channel>
			<add-channel id="testChannel2">
				<type>testBinding:testChannelTypeId</type>
				<label>Test Label</label>
				<tags>
					<tag>Tag1</tag>
					<tag>Tag2</tag>
				</tags>
			</add-channel>
			<add-channel id="testChannel3">
				<type>testBinding:testChannelTypeId</type>
				<label>Test Label</label>
				<description>Test Description</description>
			</add-channel>
		</instruction-set>
	</thing-type>

	<thing-type uid="testBinding:testThingTypeRemove">
		<instruction-set targetVersion="1">
			<remove-channel id="testChannel"/>
		</instruction-set>
	</thing-type>

	<thing-type uid="testBinding:testThingTypeUpdate">
		<instruction-set targetVersion="1">
			<update-channel id="testChannel1">
				<type>testBinding:testChannelNewTypeId</type>
				<label>New Test Label</label>
			</update-channel>
			<update-channel id="testChannel2" preserveConfiguration="false">
				<type>testBinding:testChannelNewTypeId</type>
			</update-channel>
		</instruction-set>
	</thing-type>

	<thing-type uid="testBinding:testThingTypeGroupAdd">
		<instruction-set targetVersion="1">
			<add-channel id="testChannel1" groupIds="group1,group2">
				<type>testBinding:testChannelTypeId</type>
			</add-channel>
		</instruction-set>
	</thing-type>

</update:update-descriptions>
